import { ASSESSABILITY_STATUSES, AUDITION_CONTEXTS, BRIEF_MODES, COMPONENT_CRITICALITIES, COMPONENT_SOURCES, COMPONENT_TYPES, CRITICALITY_SOURCES, DECLARED_OR_DETECTED_STATUSES, EVIDENCE_MODALITIES, EVIDENCE_SUFFICIENCIES, PERFORMER_LEVELS, PUBLIC_CLAIM_TYPES, TRUTH_STATES, VALIDATOR_ACTIONS, type Component, type ComponentCriticality, type EvidenceAnchor, type PublicClaimTrace, type QAValidationResult, type UserInputContext } from './types';
import { classifyField } from './privacy-boundary';
import { runUKEnglishGate } from './uk-english-gate';
const has = <T extends readonly string[]>(v:string, arr:T) => (arr as readonly string[]).includes(v);
export const isPerformerLevel=(v:string)=>has(v,PERFORMER_LEVELS); export const isBriefMode=(v:string)=>has(v,BRIEF_MODES); export const isAuditionContext=(v:string)=>has(v,AUDITION_CONTEXTS); export const isTruthState=(v:string)=>has(v,TRUTH_STATES); export const isComponentType=(v:string)=>has(v,COMPONENT_TYPES); export const isCriticality=(v:string)=>has(v,COMPONENT_CRITICALITIES); export const isAssessabilityStatus=(v:string)=>has(v,ASSESSABILITY_STATUSES); export const isValidatorAction=(v:string)=>has(v,VALIDATOR_ACTIONS);
export const isEvidenceSufficiency=(v:string)=>has(v,EVIDENCE_SUFFICIENCIES); export const isEvidenceAnchorModality=(v:string)=>has(v,EVIDENCE_MODALITIES); export const isComponentSource=(v:string)=>has(v,COMPONENT_SOURCES); export const isDeclaredOrDetectedStatus=(v:string)=>has(v,DECLARED_OR_DETECTED_STATUSES); export const isCriticalitySource=(v:string)=>has(v,CRITICALITY_SOURCES); export const isPublicClaimType=(v:string)=>has(v,PUBLIC_CLAIM_TYPES);
const q=(id:string,action:QAValidationResult['action'],severity:QAValidationResult['severity'],msg:string,passed:boolean):QAValidationResult=>({validation_id:id,validator_name:id,action,severity,message:msg,passed});
export const validateTimestampWithinDuration=(t?:number,d?:number)=> t===undefined || (typeof t==='number' && t>=0 && (d===undefined || t<=d));
export const validateTimeRangeWithinDuration=(r?:{start:number;end:number},d?:number)=> !r || (r.start>=0 && r.end>r.start && (d===undefined || r.end<=d));
export function sortEvidenceAnchorsChronologically<T extends {timestamp?:number}>(a:T[]){ return [...a].sort((x,y)=>(x.timestamp??0)-(y.timestamp??0)); }
export function isEvidenceAnchorPublicEligibleForFutureCuration(a: EvidenceAnchor){ return a.public_safe_flag && a.assessability_status==='sufficient' && a.evidence_sufficiency!=='insufficient'; }
export function validateEvidenceAnchor(a: EvidenceAnchor, duration?:number): QAValidationResult[] { const out:QAValidationResult[]=[]; if(!isEvidenceAnchorModality(a.modality)) out.push(q('evidence-anchor','block_report','P0','Invalid modality',false)); if(!isTruthState(a.truth_state)) out.push(q('evidence-anchor','warn','P1','Invalid truth state',false)); if(!isAssessabilityStatus(a.assessability_status)) out.push(q('evidence-anchor','block_report','P0','Invalid assessability status',false)); if(!isEvidenceSufficiency(a.evidence_sufficiency)) out.push(q('evidence-anchor','block_report','P0','Invalid evidence sufficiency',false)); if(!validateTimestampWithinDuration(a.timestamp,duration)) out.push(q('evidence-anchor','warn','P1','Invalid timestamp',false)); if(!validateTimeRangeWithinDuration(a.time_range,duration)) out.push(q('evidence-anchor','warn','P1','Invalid time range',false)); if(['video','audio','transcript'].includes(a.modality) && !a.timestamp && !a.time_range && !['not_present','not_relevant','not_assessable','unsupported_inference_blocked'].includes(a.assessability_status)) out.push(q('evidence-anchor','warn','P1','Missing temporal anchor',false)); if(['not_assessable','not_present','not_relevant','unsupported_inference_blocked'].includes(a.assessability_status) && a.evidence_sufficiency==='sufficient') out.push(q('evidence-anchor','block_report','P0','Limitation cannot be sufficient evidence',false)); if(/chain-of-thought|hidden reasoning/i.test(a.observation)) out.push(q('evidence-anchor','block_report','P0','Hidden reasoning is forbidden',false)); return out; }
export function validateComponent(c: Component): QAValidationResult[] { const out:QAValidationResult[]=[]; if(!isComponentType(c.component_type)) out.push(q('component','block_report','P0','Invalid component type',false)); if(!isComponentSource(c.source)) out.push(q('component','block_report','P0','Invalid component source',false)); if(!isDeclaredOrDetectedStatus(c.declared_or_detected_status)) out.push(q('component','warn','P1','Invalid declared/detected status',false)); if(!isTruthState(c.source_truth_state)) out.push(q('component','warn','P1','Invalid component truth state',false)); if(!validateTimeRangeWithinDuration(c.start_time!==undefined&&c.end_time!==undefined?{start:c.start_time,end:c.end_time}:undefined)) out.push(q('component','warn','P1','Invalid component time range',false)); return out; }
export function validateComponentCriticality(c: ComponentCriticality){ if(!isCriticality(c.criticality) || !isCriticalitySource(c.criticality_source)) return q('component-criticality','block_report','P0','Invalid criticality',false); if(c.criticality==='essential' && c.criticality_source==='uncertain') return q('component-criticality','warn','P1','Essential needs stronger source',false); return q('component-criticality','pass','P2','Valid criticality',true); }
export function defaultCriticalityForComponentType(t:string){ return t==='slate_ident' ? 'administrative' : 'unknown'; }
export function canCriticalityBecomeFutureHardGate(c: ComponentCriticality){ return c.criticality==='essential' && c.criticality_source!=='uncertain' && c.confidence>=0.7; }
export function createComponentStabilitySignature(components: Component[]){ return components.map((c)=>`${c.component_type}:${c.start_time??0}-${c.end_time??0}`).sort().join('|'); }
export function compareComponentStabilitySignatures(a:string,b:string){ return { stable:a===b, reason:a===b?'match':'mismatch' }; }
export function validatePublicClaimTrace(claim: PublicClaimTrace, hasPublicOutput:boolean){ if(!isPublicClaimType(claim.claim_type)) return q('claim-trace','block_report','P0','Invalid claim type',false); if(claim.claim_type!=='internal_only' && claim.evidence_anchor_ids.length===0) return q('claim-trace',hasPublicOutput?'block_report':'warn',hasPublicOutput?'P0':'P1','Missing evidence anchors',false); if(claim.public_text && /hidden reasoning|chain-of-thought/i.test(claim.public_text)) return q('claim-trace','block_report','P0','Hidden reasoning in public text',false); return q('claim-trace','pass','P2','Valid claim trace',true); }
export function validateInputCompleteness(input: Partial<UserInputContext> & {take_id?:string; media_asset_id?:string}){ const out:QAValidationResult[]=[]; if(!input.take_id && !input.media_asset_id) out.push(q('input-completeness','block_report','P0','Missing take/upload reference',false)); if(!input.performer_level || !isPerformerLevel(input.performer_level)) out.push(q('input-completeness','block_report','P0','Missing or invalid performer level',false)); if(!input.brief_mode || !isBriefMode(input.brief_mode)) out.push(q('input-completeness','block_report','P0','Missing or invalid brief mode',false)); return out; }
export function validateTruthStateMisuse(publicOutput:boolean, truthState:string){ if(isTruthState(truthState)) return q('truth-state-misuse','pass','P2','Valid truth state',true); return q('truth-state-misuse',publicOutput?'block_report':'warn',publicOutput?'P0':'P1','Invalid truth state usage',false); }
export function validateNoBriefInvention(mode:string, claim:string, publicOutput:boolean){ const invented = mode==='no_brief_baseline' && /role|character|brand|audience|time limit/i.test(claim); if(!invented) return q('no-brief-invention','pass','P2','No invention detected',true); return q('no-brief-invention', publicOutput?'block_report':'suppress_claim', publicOutput?'P0':'P1', 'No-brief invention detected', false); }
export function validateMissingEvidenceAnchor(hasAnchor:boolean, publicOutput:boolean){ return hasAnchor? q('missing-evidence-anchor','pass','P2','Evidence anchor present',true) : q('missing-evidence-anchor', publicOutput?'block_report':'warn', publicOutput?'P0':'P1', 'Missing evidence anchor', false); }
export function validateMissingClaimTrace(hasClaimTrace:boolean, publicOutput:boolean){ return hasClaimTrace? q('missing-claim-trace','pass','P2','Claim trace present',true) : q('missing-claim-trace', publicOutput?'block_report':'warn', publicOutput?'P0':'P1', 'Missing public claim trace', false); }
export function validatePublicPrivateLeakage(fields:string[]){ const leaked=fields.filter((f)=>classifyField(f)!=='public_safe' && classifyField(f)!=='public_only_after_validation'); return leaked.length===0 ? q('public-private-leakage','pass','P2','No leakage detected',true) : q('public-private-leakage','block_report','P0',`Leaked: ${leaked.join(', ')}`,false); }
export function validateUKEnglish(text:string, publicOutput:boolean){ const result=runUKEnglishGate(text,{context:publicOutput?'normal_public_copy':'internal_trace'}); return result.passed ? q('uk-english','pass','P2','UK English pass',true) : q('uk-english', publicOutput?'block_report':'warn', publicOutput?'P1':'P2', `Flagged terms: ${result.flags.join(', ')}`, false); }
