import { ASSESSABILITY_STATUSES, AUDITION_CONTEXTS, BRIEF_MODES, COMPONENT_CRITICALITIES, COMPONENT_SOURCES, COMPONENT_TYPES, CRITICALITY_SOURCES, DECLARED_OR_DETECTED_STATUSES, EVIDENCE_MODALITIES, EVIDENCE_SUFFICIENCIES, PERFORMER_LEVELS, PUBLIC_CLAIM_TYPES, TRUTH_STATES, VALIDATOR_ACTIONS, type Component, type ComponentCriticality, type EvidenceAnchor, type PublicClaimTrace, type QAValidationResult, type UserInputContext } from './types';
import { ONTOLOGY_DISCIPLINES, ONTOLOGY_MATURITY_STATUSES, TECHNIQUE_OBSERVATION_STATUSES, TECHNIQUE_PUBLIC_DISPLAY_ELIGIBILITY } from './types';
import { classifyField } from './privacy-boundary';
import { runUKEnglishGate } from './uk-english-gate';
const has = <T extends readonly string[]>(v:string, arr:T) => (arr as readonly string[]).includes(v);
export const isPerformerLevel=(v:string)=>has(v,PERFORMER_LEVELS); export const isBriefMode=(v:string)=>has(v,BRIEF_MODES); export const isAuditionContext=(v:string)=>has(v,AUDITION_CONTEXTS); export const isTruthState=(v:string)=>has(v,TRUTH_STATES); export const isComponentType=(v:string)=>has(v,COMPONENT_TYPES); export const isCriticality=(v:string)=>has(v,COMPONENT_CRITICALITIES); export const isAssessabilityStatus=(v:string)=>has(v,ASSESSABILITY_STATUSES); export const isValidatorAction=(v:string)=>has(v,VALIDATOR_ACTIONS);
export const isEvidenceSufficiency=(v:string)=>has(v,EVIDENCE_SUFFICIENCIES); export const isEvidenceAnchorModality=(v:string)=>has(v,EVIDENCE_MODALITIES); export const isComponentSource=(v:string)=>has(v,COMPONENT_SOURCES); export const isDeclaredOrDetectedStatus=(v:string)=>has(v,DECLARED_OR_DETECTED_STATUSES); export const isCriticalitySource=(v:string)=>has(v,CRITICALITY_SOURCES); export const isPublicClaimType=(v:string)=>has(v,PUBLIC_CLAIM_TYPES);
const q=(id:string,action:QAValidationResult['action'],severity:QAValidationResult['severity'],msg:string,passed:boolean):QAValidationResult=>({validation_id:id,validator_name:id,action,severity,message:msg,passed});
export const validateTimestampWithinDuration=(t?:number,d?:number)=> t===undefined || (typeof t==='number' && t>=0 && (d===undefined || t<=d));
export const validateTimeRangeWithinDuration=(r?:{start:number;end:number},d?:number)=> !r || (r.start>=0 && r.end>r.start && (d===undefined || r.end<=d));
export function sortEvidenceAnchorsChronologically<T extends {timestamp?:number}>(a:T[]){ return [...a].sort((x,y)=>(x.timestamp??0)-(y.timestamp??0)); }
export function isEvidenceAnchorPublicEligibleForFutureCuration(a: EvidenceAnchor){ return a.public_safe_flag && a.assessability_status==='sufficient' && a.evidence_sufficiency!=='insufficient'; }
export function validateEvidenceAnchor(a: EvidenceAnchor, duration?:number): QAValidationResult[] { const out:QAValidationResult[]=[]; if(!isEvidenceAnchorModality(a.modality)) out.push(q('evidence-anchor','block_report','P0','Invalid modality',false)); if(!isTruthState(a.truth_state)) out.push(q('evidence-anchor','warn','P1','Invalid truth state',false)); if(!isAssessabilityStatus(a.assessability_status)) out.push(q('evidence-anchor','block_report','P0','Invalid assessability status',false)); if(!isEvidenceSufficiency(a.evidence_sufficiency)) out.push(q('evidence-anchor','block_report','P0','Invalid evidence sufficiency',false)); if(!validateTimestampWithinDuration(a.timestamp,duration)) out.push(q('evidence-anchor','warn','P1','Invalid timestamp',false)); if(!validateTimeRangeWithinDuration(a.time_range,duration)) out.push(q('evidence-anchor','warn','P1','Invalid time range',false)); if(['video','audio','transcript'].includes(a.modality) && !a.timestamp && !a.time_range && !['not_present','not_relevant','not_assessable','unsupported_inference_blocked'].includes(a.assessability_status)) out.push(q('evidence-anchor','warn','P1','Missing temporal anchor',false)); if(['not_assessable','not_present','not_relevant','unsupported_inference_blocked'].includes(a.assessability_status) && a.evidence_sufficiency==='sufficient') out.push(q('evidence-anchor','block_report','P0','Limitation cannot be sufficient evidence',false)); if(/chain-of-thought|hidden reasoning/i.test(a.observation)) out.push(q('evidence-anchor','block_report','P0','Hidden reasoning is forbidden',false)); return out; }
export function validateComponent(c: Component): QAValidationResult[] { const out:QAValidationResult[]=[]; if(!isComponentType(c.component_type)) out.push(q('component','block_report','P0','Invalid component type',false)); if(!isComponentSource(c.source)) out.push(q('component','block_report','P0','Invalid component source',false)); if(!isDeclaredOrDetectedStatus(c.declared_or_detected_status)) out.push(q('component','warn','P1','Invalid declared/detected status',false)); if(!isTruthState(c.source_truth_state)) out.push(q('component','warn','P1','Invalid component truth state',false)); if(!validateTimeRangeWithinDuration(c.start_time!==undefined&&c.end_time!==undefined?{start:c.start_time,end:c.end_time}:undefined)) out.push(q('component','warn','P1','Invalid component time range',false)); return out; }
export function validateComponentCriticality(c: ComponentCriticality){ if(!isCriticality(c.criticality) || !isCriticalitySource(c.criticality_source)) return q('component-criticality','block_report','P0','Invalid criticality',false); if(c.criticality==='essential' && c.criticality_source==='uncertain') return q('component-criticality','warn','P1','Essential needs stronger source',false); return q('component-criticality','pass','P2','Valid criticality',true); }
export function defaultCriticalityForComponentType(t:string){ return t==='slate_ident' ? 'administrative' : 'unknown'; }
export function canCriticalityBecomeFutureHardGate(c: ComponentCriticality){ return c.criticality==='essential' && c.criticality_source!=='uncertain' && c.confidence>=0.7; }
export function createComponentStabilitySignature(components: Component[]){ return components.map((c)=>`${c.component_type}:${c.start_time??0}-${c.end_time??0}`).sort().join('|'); }
export function compareComponentStabilitySignatures(a:string,b:string){ return { stable:a===b, reason:a===b?'match':'mismatch' }; }
export function validatePublicClaimTrace(claim: PublicClaimTrace, hasPublicOutput:boolean){ if(!isPublicClaimType(claim.claim_type)) return q('claim-trace','block_report','P0','Invalid claim type',false); if(claim.claim_type!=='internal_only' && claim.evidence_anchor_ids.length===0) return q('claim-trace',hasPublicOutput?'block_report':'warn',hasPublicOutput?'P0':'P1','Missing evidence anchors',false); if(claim.public_text && /hidden reasoning|chain-of-thought/i.test(claim.public_text)) return q('claim-trace','block_report','P0','Hidden reasoning in public text',false); return q('claim-trace','pass','P2','Valid claim trace',true); }
export function validateInputCompleteness(input: Partial<UserInputContext> & {take_id?:string; media_asset_id?:string}){ const out:QAValidationResult[]=[]; if(!input.take_id && !input.media_asset_id) out.push(q('input-completeness','block_report','P0','Missing take/upload reference',false)); if(!input.performer_level || !isPerformerLevel(input.performer_level)) out.push(q('input-completeness','block_report','P0','Missing or invalid performer level',false)); if(!input.brief_mode || !isBriefMode(input.brief_mode)) out.push(q('input-completeness','block_report','P0','Missing or invalid brief mode',false)); return out; }
export function validateTruthStateMisuse(publicOutput:boolean, truthState:string){ if(isTruthState(truthState)) return q('truth-state-misuse','pass','P2','Valid truth state',true); return q('truth-state-misuse',publicOutput?'block_report':'warn',publicOutput?'P0':'P1','Invalid truth state usage',false); }
export function validateNoBriefInvention(mode:string, claim:string, publicOutput:boolean){ const invented = mode==='no_brief_baseline' && /role|character|brand|audience|time limit/i.test(claim); if(!invented) return q('no-brief-invention','pass','P2','No invention detected',true); return q('no-brief-invention', publicOutput?'block_report':'suppress_claim', publicOutput?'P0':'P1', 'No-brief invention detected', false); }
export function validateMissingEvidenceAnchor(hasAnchor:boolean, publicOutput:boolean){ return hasAnchor? q('missing-evidence-anchor','pass','P2','Evidence anchor present',true) : q('missing-evidence-anchor', publicOutput?'block_report':'warn', publicOutput?'P0':'P1', 'Missing evidence anchor', false); }
export function validateMissingClaimTrace(hasClaimTrace:boolean, publicOutput:boolean){ return hasClaimTrace? q('missing-claim-trace','pass','P2','Claim trace present',true) : q('missing-claim-trace', publicOutput?'block_report':'warn', publicOutput?'P0':'P1', 'Missing public claim trace', false); }
export function validatePublicPrivateLeakage(fields:string[]){ const leaked=fields.filter((f)=>classifyField(f)!=='public_safe' && classifyField(f)!=='public_only_after_validation'); return leaked.length===0 ? q('public-private-leakage','pass','P2','No leakage detected',true) : q('public-private-leakage','block_report','P0',`Leaked: ${leaked.join(', ')}`,false); }


export const isOntologyMaturityStatus=(v:string)=>has(v,ONTOLOGY_MATURITY_STATUSES);
export const isOntologyDiscipline=(v:string)=>has(v,ONTOLOGY_DISCIPLINES);
export const isTechniqueObservationStatus=(v:string)=>has(v,TECHNIQUE_OBSERVATION_STATUSES);
export const isTechniquePublicDisplayEligibility=(v:string)=>has(v,TECHNIQUE_PUBLIC_DISPLAY_ELIGIBILITY);
export const isSourceHierarchyLevel=(n:number)=>[1,2,3,4,5,6].includes(n);

export function isOntologyItemUsableInS3Shadow(m:string){ return m==='research_seed' || m==='expert_reviewed'; }
export function assertNoProductionSafeInS3(m:string){ if(m==='production_safe') throw new Error('production_safe forbidden in S3'); }
export function validateOntologyMaturityUse(m:string){ return isOntologyMaturityStatus(m) && m!=='production_safe' ? q('ontology-maturity','pass','P2','Maturity allowed for S3 shadow',true) : q('ontology-maturity','block_report','P0','Maturity not allowed for S3 shadow',false); }
export function validateOntologyItemHasSafetyRequirements(i:any){ return i.false_positive_risks?.length>0 && i.assessability_requirements?.length>0 && i.evidence_required?.length>0; }
export function validateOntologyItemSourceProvenance(i:any){ return (i.source_provenance_ids?.length??0)>0 || (i.release_maturity==='research_seed' && /limitation/i.test(i.maturity_notes||'')); }
export function validateOntologyItemPublicCandidateIsNotPublic(){ return q('ontology-public-candidate','block_report','P0','Public candidate wording cannot be rendered in S3',false); }
export function validateOntologyItem(i:any){ const out=[] as QAValidationResult[]; if(!isOntologyDiscipline(i.discipline)) out.push(q('ontology-item','block_report','P0','Invalid ontology discipline',false)); if(!isOntologyMaturityStatus(i.release_maturity)) out.push(q('ontology-item','block_report','P0','Invalid ontology maturity',false)); if(i.release_maturity==='production_safe') out.push(q('ontology-item','block_report','P0','production_safe forbidden in S3',false)); if(!validateOntologyItemHasSafetyRequirements(i)) out.push(q('ontology-item','block_report','P0','Missing safety requirements',false)); if(!validateOntologyItemSourceProvenance(i)) out.push(q('ontology-item','warn','P1','Missing source provenance for non-research item',false)); return out; }
export function validateOntologyVersion(v:any){ const out=[] as QAValidationResult[]; if(!v.included_item_ids?.length) out.push(q('ontology-version','block_report','P0','Missing included item ids',false)); if(/production_safe/i.test(v.release_maturity_summary||'')) out.push(q('ontology-version','block_report','P0','Production safe summary forbidden in S3',false)); return out; }
export function validateOntologyVersionNotProductionSafeInS3(v:any){ return /production_safe/i.test(v.release_maturity_summary||'') ? q('ontology-version','block_report','P0','Production safe forbidden in S3',false) : q('ontology-version','pass','P2','Shadow version allowed',true); }
export function validateSourceDoesNotCreateScoringAuthority(s:any){ return /(grade|percentage|syllabi|weight)/i.test((s.supports||[]).join(' ')) ? q('source-provenance','block_report','P0','Scoring authority import forbidden',false) : q('source-provenance','pass','P2','No scoring authority import',true); }
export function validateSourceProvenance(s:any){ const out=[] as QAValidationResult[]; if(!isSourceHierarchyLevel(s.source_hierarchy_level)) out.push(q('source-provenance','block_report','P0','Invalid source hierarchy level',false)); if(!s.limitation_notes) out.push(q('source-provenance','warn','P1','Missing limitation notes',false)); const auth=validateSourceDoesNotCreateScoringAuthority(s); if(!auth.passed) out.push(auth); return out; }
export function validateUnsafeWordingPresent(m:any){ return m.unsafe_phrase ? q('safe-language-map','pass','P2','Unsafe wording captured',true) : q('safe-language-map','warn','P1','Unsafe wording missing',false); }
export function validateCandidatePublicLanguageBlockedInS3(){ return q('safe-language-map','block_report','P0','Public language rendering blocked in S3',false); }
export function validateSafePublicLanguageMap(m:any){ const out=[] as QAValidationResult[]; if(!m.unsafe_phrase) out.push(q('safe-language-map','warn','P1','Missing unsafe phrase',false)); if(!isOntologyMaturityStatus(m.maturity_required_for_public_use)) out.push(q('safe-language-map','warn','P1','Invalid maturity requirement',false)); return out; }
export function validateRecognitionTestResult(r:any){ const out=[] as QAValidationResult[]; if(typeof r.pass!=='boolean') out.push(q('recognition-test','warn','P1','Invalid pass flag',false)); if(typeof r.confidence!=='number') out.push(q('recognition-test','warn','P1','Invalid confidence',false)); return out; }
export function validateRecognitionTestDoesNotPromoteMaturityInS3(){ return q('recognition-test','block_report','P0','Recognition results cannot promote maturity in S3',false); }
export function classifyTechniqueConfidence(c:number){ if(c<0.55) return 'blocked_or_uncertain'; if(c<0.75) return 'uncertain_only'; if(c<0.85) return 'shadow_observed'; return 'future_review_candidate'; }
export function validateTechniqueConfidenceForStatus(c:number,status:string){ const cls=classifyTechniqueConfidence(c); if(status==='observed' && cls!=='shadow_observed' && cls!=='future_review_candidate') return q('technique-confidence','block_report','P0','Low confidence cannot be observed',false); return q('technique-confidence','pass','P2','Technique confidence acceptable',true); }
export function validateTechniqueFutureReviewEligibility(c:number,maturity:string,fp:boolean){ if(c<0.85 || !['expert_reviewed','benchmark_validated'].includes(maturity) || !fp) return q('technique-future-review','block_report','P0','Future review eligibility not met',false); return q('technique-future-review','pass','P2','Future review eligibility met',true); }
export function validateFalsePositiveChecks(txt:string[]){ return txt.length===0 ? q('technique-fp','block_report','P0','False-positive checks missing',false) : q('technique-fp','pass','P2','False-positive checks recorded',true); }
export function validateTechniqueObservationLinks(o:any){ return (!o.evidence_anchor_id || !o.ontology_item_id) ? q('technique-links','block_report','P0','Missing evidence or ontology link',false) : q('technique-links','pass','P2','Links valid',true); }
export function validateTechniqueObservationS3Privacy(){ return q('technique-privacy','pass','P2','Technique observation stays private in S3',true); }
export function validateTechniqueObservationDoesNotScore(input:any){ return input?.score_input===true ? q('technique-score','block_report','P0','Technique-as-score blocked in S3',false) : q('technique-score','pass','P2','No scoring use',true); }
export function validateTechniqueObservationPublicDisplayBlocked(display:string){ return display==='not_public_s3' || display.startsWith('blocked_') || display==='eligible_for_future_review' ? q('technique-display','pass','P2','Display state accepted for S3 shadow',true) : q('technique-display','block_report','P0','Public display not allowed in S3',false); }
export function validateTechniqueObservation(o:any){ const out=[] as QAValidationResult[]; if(!isTechniqueObservationStatus(o.status)) out.push(q('technique-observation','block_report','P0','Invalid observation status',false)); if(!isTechniquePublicDisplayEligibility(o.public_display_eligibility)) out.push(q('technique-observation','block_report','P0','Invalid public display eligibility',false)); const link=validateTechniqueObservationLinks(o); if(!link.passed) out.push(link); out.push(validateTechniqueObservationDoesNotScore(o)); if(o.evidence_sufficiency==='insufficient' && o.status==='observed') out.push(q('technique-observation','block_report','P0','Insufficient evidence cannot be observed',false)); const c=validateTechniqueConfidenceForStatus(o.confidence,o.status); if(!c.passed) out.push(c); return out; }

export function validateUKEnglish(text:string, publicOutput:boolean){ const result=runUKEnglishGate(text,{context:publicOutput?'normal_public_copy':'internal_trace'}); return result.passed ? q('uk-english','pass','P2','UK English pass',true) : q('uk-english', publicOutput?'block_report':'warn', publicOutput?'P1':'P2', `Flagged terms: ${result.flags.join(', ')}`, false); }
