import { describe, expect, it } from 'vitest';
import { EvidenceAnchor, Component, ComponentCriticality, PublicClaimTrace } from '@/server/v3/types';
import { validateComponent, validateComponentCriticality, validateEvidenceAnchor, validateNoBriefInvention, validatePublicClaimTrace, validateTruthStateMisuse, validateUKEnglish, createComponentStabilitySignature, compareComponentStabilitySignatures } from '@/server/v3/validation';
import { runS2Harness, getS2MetricRegistry } from '@/server/v3/evaluation-harness';
import { getFixtureRegistry, getRedTeamRegistry } from '@/server/v3/evaluation-harness';

const anchor: EvidenceAnchor = { anchor_id:'a1', take_id:'t1', modality:'video', truth_state:'observed_in_tape', observation:'Clear self-tape evidence', confidence:0.9, assessability_status:'sufficient', evidence_sufficiency:'sufficient', timestamp:10, public_safe_flag:false };
const component: Component = { component_id:'c1', take_id:'t1', component_type:'acting_scene', source:'observed_in_tape', confidence:0.8, assessability_status:'sufficient', evidence_sufficiency:'sufficient', declared_or_detected_status:'detected', source_truth_state:'observed_in_tape' };
const criticality: ComponentCriticality = { component_id:'c1', criticality:'administrative', criticality_source:'default', confidence:0.8 };
const claim: PublicClaimTrace = { claim_id:'p1', take_id:'t1', claim_type:'evidence_observation', evidence_anchor_ids:['a1'], truth_state:'observed_in_tape', validator_status:'pass' };

describe('v3 s2 evidence/component/claim trace', () => {
  it('evidence anchor validates', () => { expect(validateEvidenceAnchor(anchor, 120).length).toBe(0); });
  it('evidence anchor temporal and limitation rules', () => { expect(validateEvidenceAnchor({ ...anchor, timestamp:-1 },120).some((r)=>!r.passed)).toBe(true); expect(validateEvidenceAnchor({ ...anchor, time_range:{start:20,end:10}},120).some((r)=>!r.passed)).toBe(true); expect(validateEvidenceAnchor({ ...anchor, assessability_status:'not_assessable', evidence_sufficiency:'sufficient' },120).some((r)=>r.action==='block_report')).toBe(true); });
  it('component and criticality validate', () => { expect(validateComponent(component).length).toBe(0); expect(validateComponent({ ...component, component_type:'bad' as never }).some((r)=>!r.passed)).toBe(true); expect(validateComponentCriticality(criticality).passed).toBe(true); expect(validateComponentCriticality({ ...criticality, criticality:'essential', criticality_source:'uncertain' }).action).toBe('warn'); });
  it('claim validation and text safety', () => { expect(validatePublicClaimTrace(claim, true).passed).toBe(true); expect(validatePublicClaimTrace({ ...claim, evidence_anchor_ids:[] }, true).action).toBe('block_report'); expect(validatePublicClaimTrace({ ...claim, public_text:'hidden reasoning' }, true).action).toBe('block_report'); });
  it('traceability validators', () => { expect(validateNoBriefInvention('no_brief_baseline','Role claim',false).action).toBe('suppress_claim'); expect(validateTruthStateMisuse(true,'bad').action).toBe('block_report'); expect(validateUKEnglish('callback',true).action).toBe('block_report'); });
  it('gf-01 stability signature warning path', () => { const s1=createComponentStabilitySignature([{...component, component_type:'acting_scene',start_time:0,end_time:50},{...component, component_id:'c2',component_type:'song',start_time:50,end_time:100}]); const s2=createComponentStabilitySignature([{...component, component_type:'acting_scene',start_time:0,end_time:40},{...component, component_id:'c2',component_type:'song',start_time:40,end_time:90},{...component, component_id:'c3',component_type:'slate_ident',start_time:90,end_time:100}]); expect(compareComponentStabilitySignatures(s1,s2).stable).toBe(false); });
  it('s2 harness metrics and fixture mapping', () => { expect(getS2MetricRegistry()).toHaveLength(20); expect(runS2Harness('GF-01').checks).toHaveLength(20); const gf01=getFixtureRegistry().find((f)=>f.id==='GF-01')!; expect(gf01.required_s2_artefacts).toContain('component_stability_comparison'); expect(getRedTeamRegistry().find((r)=>r.id==='RT-15')!.fixture_links).toContain('GF-01'); });
});
