import { describe, expect, it } from 'vitest';
import { V3_FLAG_DEFAULTS } from '@/server/v3/flags';
import { assertS1ReleaseStateAllowed, isLaunchReadinessState, isS1AllowedReleaseState } from '@/server/v3/release-state';
import { BRIEF_MODES, PERFORMER_LEVEL_LABELS, PERFORMER_LEVELS } from '@/server/v3/types';
import { canSurfaceField, classifyField, isObjectPublicByDefault, redactPrivateFields } from '@/server/v3/privacy-boundary';
import { runUKEnglishGate } from '@/server/v3/uk-english-gate';
import { isAssessabilityStatus, isAuditionContext, isBriefMode, isComponentType, isCriticality, isPerformerLevel, isTruthState, isValidatorAction, validateInputCompleteness, validateMissingClaimTrace, validateMissingEvidenceAnchor, validateNoBriefInvention, validatePublicPrivateLeakage, validateTruthStateMisuse, validateUKEnglish } from '@/server/v3/validation';
import { getFixtureRegistry, getMetricRegistry, getRedTeamRegistry, runS1Harness } from '@/server/v3/evaluation-harness';

describe('v3 s1 closure defects fix', () => {
  it('flags default false', ()=> expect(Object.values(V3_FLAG_DEFAULTS).every((v)=>v===false)).toBe(true));
  it('s1 release gating', ()=>{ expect(isS1AllowedReleaseState('design_only')).toBe(true); expect(isS1AllowedReleaseState('dark_mode_internal')).toBe(true); expect(()=>assertS1ReleaseStateAllowed('launch')).toThrow(); expect(()=>assertS1ReleaseStateAllowed('internal_rendered_QA')).toThrow(); expect(()=>assertS1ReleaseStateAllowed('branch_limited_readiness')).toThrow(); expect(isLaunchReadinessState('hidden_production_beta')).toBe(false);});
  it('runtime enum validators', ()=>{ expect(isPerformerLevel('professional')).toBe(true); expect(isPerformerLevel('bad')).toBe(false); expect(isBriefMode('comparison')).toBe(false); expect(BRIEF_MODES).not.toContain('known_material'); expect(BRIEF_MODES).not.toContain('hybrid_multi_discipline'); expect(isAuditionContext('song_voice')).toBe(true); expect(isTruthState('observed_in_tape')).toBe(true); expect(isComponentType('song')).toBe(true); expect(isCriticality('essential')).toBe(true); expect(isAssessabilityStatus('partial')).toBe(true); expect(isValidatorAction('warn')).toBe(true); });
  it('uk performer labels exist', ()=> expect(PERFORMER_LEVELS.map((l)=>PERFORMER_LEVEL_LABELS[l])).toEqual(['Learning / School','Amateur / Community','Emerging / Training','Professional']));
  it('privacy boundary classification', ()=>{ expect(classifyField('user_id')).toBe('sensitive'); expect(classifyField('hidden_reasoning')).toBe('private_trace'); expect(isObjectPublicByDefault('EvidenceAnchor')).toBe(false); expect(canSurfaceField('selected_level_label',true)).toBe(true); expect(canSurfaceField('full_brief_text',true)).toBe(false); expect(redactPrivateFields({ user_id:'u', selected_level_label:'Professional', access_setup_context:'x' })).toEqual({}); });
  it('uk english contexts', ()=>{ expect(runUKEnglishGate('self-tape recall',{context:'normal_public_copy'}).passed).toBe(true); expect(runUKEnglishGate('callback',{context:'normal_public_copy'}).passed).toBe(false); expect(runUKEnglishGate('"callback"',{context:'quoted_or_supplied_material'}).passed).toBe(true); expect(runUKEnglishGate('callback',{context:'red_team_case'}).passed).toBe(true); expect(runUKEnglishGate('analyse behaviour',{context:'normal_public_copy'}).passed).toBe(true); expect(runUKEnglishGate('analyze behavior',{context:'normal_public_copy'}).passed).toBe(false); });
  it('validator matrix', ()=>{ expect(validateInputCompleteness({performer_level:'professional',brief_mode:'full_casting_brief'} as never).some((r)=>r.action==='block_report')).toBe(true); expect(validateTruthStateMisuse(false,'invalid').action).toBe('warn'); expect(validateTruthStateMisuse(true,'invalid').action).toBe('block_report'); expect(validateNoBriefInvention('no_brief_baseline','Role is X',false).action).toBe('suppress_claim'); expect(validateNoBriefInvention('no_brief_baseline','Role is X',true).action).toBe('block_report'); expect(validateMissingEvidenceAnchor(false,false).action).toBe('warn'); expect(validateMissingEvidenceAnchor(false,true).action).toBe('block_report'); expect(validateMissingClaimTrace(false,true).action).toBe('block_report'); expect(validatePublicPrivateLeakage(['user_id']).action).toBe('block_report'); expect(validateUKEnglish('callback',true).action).toBe('block_report'); expect(validateUKEnglish('callback',false).action).toBe('pass'); });
  it('fixtures and red-team richness', ()=>{ const gf=getFixtureRegistry(); const rt=getRedTeamRegistry(); expect(gf).toHaveLength(20); expect(rt).toHaveLength(17); const gf01=gf.find((f)=>f.id==='GF-01')!; expect(gf01.priority).toBe('P0'); expect(gf01.linked_red_team_ids).toContain('RT-15'); expect(gf01.later_expected_report_comparison_behaviour.join(' ')).toContain('Take 1=98'); expect(gf01.later_expected_report_comparison_behaviour.join(' ')).toContain('Submit Take 1'); expect(gf.every((f)=>f.purpose && f.expected_input_dimensions.length>0 && f.release_gate)).toBe(true); const rt15=rt.find((r)=>r.id==='RT-15')!; expect(rt15.fixture_links).toContain('GF-01'); expect(rt.every((r)=>r.unsafe_behaviour && r.expected_validator && r.expected_action && r.release_gate)).toBe(true); });
  it('harness metrics and qa results', ()=>{ const metrics=getMetricRegistry(); expect(metrics.length).toBeGreaterThanOrEqual(15); const result=runS1Harness('GF-01',{ 'GF-01 registered as P0 comparison failure fixture': true },[{validation_id:'v',validator_name:'x',action:'pass',severity:'P2',passed:true}]); expect(result.checks).toHaveLength(15); expect(result.validations).toHaveLength(1); });
});
