import { describe, expect, it } from 'vitest';
import { assertNoPrivateTraceRendered, renderInternalQAReport, redactPublicReportForInternalRender, type InternalQARenderInput } from '@/server/v3/s5-internal-renderer';
import type { PublicReportV3 } from '@/server/v3/s5-public-report';
import { getS5RendererMetricRegistry } from '@/server/v3/evaluation-harness';
import { GOLDEN_FIXTURES } from '@/server/v3/fixtures';

const report: PublicReportV3 = {
  schema_version:'tapecoach_v3',report_id:'r1',take_id:'t1',submission_id:'s1',selected_level:'professional',audition_summary:'Clear summary',analysis_mode:'internal',overall_readiness:'92',professional_band:'92',level_adjusted_readiness:'88',observed_quality_summary:'Good',gap_to_selected_level:'Minor gap',component_breakdown:['A'],technique_observations:[{technique_or_safe_descriptor:'timing',confidence:0.9,observed_evidence:'seen',why_it_matters:'matters',readiness_impact:'medium',next_action:'rehearse'}],discipline_summaries:['D'],why_this_score:'Evidence based',standout_delta:'small gains',priority_fixes:['fix'],strengths:['strength'],improvements:['improve'],timestamped_evidence:['00:10 note'],next_take_plan:[{group:'quick_wins',actions:[{action_text:'do X',linked_evidence_anchor_ids:['ea1'],linked_component_ids:['c1'],linked_dimension_or_technique_ids:['d1'],why_it_matters:'why',level_relevance:'pro',rehearsal_only_or_recorded_take_ready:'recorded_take_ready',expected_band_impact:'up'}]}],assessability_notes:['partial audio'],limitations:['noise'],brief_or_task_fit:'Aligned',role_or_material_context:'Context',critical_component_gates:['gate note'],submission_cohesion:'stable',comparison_summary:{status:'placeholder_only_no_recommendation',note:'comparison not available in S5'},safety_public_notes:['safe'],export_metadata:{placeholder_only:true},optional_summary_categories:['x'],claim_traces:[{report_claim_id:'rc1',report_section:'overall_readiness',claim_type:'score',public_safe_text:'safe',linked_evidence_anchor_ids:['ea1'],linked_public_claim_trace_ids:['pc1'],truth_state_key:'observed_in_tape',validator_status:'pass'}]
};
const input: InternalQARenderInput = { public_report_v3:report, validator_trace_summary:[{validation_id:'v1',validator_name:'report-claim-traces',action:'pass',severity:'P2',passed:true,message:'ok'}], evidence_to_report_trace_map: report.claim_traces, redaction_result:'pass', uk_english_result:{passed:true,flags:[]}, report_depth_score:{score:80,status:'ok',notes_safe:'ok',missing_sections:[],generic_phrase_count:0,timestamp_usefulness:'high',next_take_plan_usefulness:'high',level_appropriate_detail:'high'}, actionability_score:{score:82,status:'ok',notes_safe:'ok',missing_sections:[],generic_phrase_count:0,timestamp_usefulness:'high',next_take_plan_usefulness:'high',level_appropriate_detail:'high'}, release_state:'internal_rendered_QA', internal_qa_marker:true };

describe('s5 internal renderer',()=>{
 it('accepts minimal valid public report',()=>{ const out=renderInternalQAReport(input); expect(out.blocked_public_release).toBe(true); });
 it('comparison placeholder suppresses unsafe wording',()=>{ const bad={...report,comparison_summary:{status:'placeholder_only_no_recommendation',note:'Submit Take 1 winner best take'}} as PublicReportV3; const out=renderInternalQAReport({...input,public_report_v3:bad}); const c=out.sections.find((s)=>s.section_id==='comparison_placeholder')!; expect(c.safe_text.join(' ')).not.toMatch(/submit take|winner|best take/i); });
 it('renders full 21-section map',()=>{ const out=renderInternalQAReport(input); expect(out.sections.filter((s)=>s.section_id!=='validator_block_notice').length).toBe(21); });
 it('redacts ids and no raw scoretrace',()=>{ const r=redactPublicReportForInternalRender(report); expect(r.claim_traces[0].report_claim_id).toContain('claim:'); expect(JSON.stringify(r)).not.toContain('ScoreTrace'); });
 it('trace display redacts ids only',()=>{ const out=renderInternalQAReport(input); expect(out.trace_rows[0].linked_evidence_anchor_ids[0]).toContain('ev:'); expect(JSON.stringify(out.trace_rows[0])).not.toContain('ea1'); });
 it('validator rows sanitise hidden reasoning',()=>{ const out=renderInternalQAReport({...input,validator_trace_summary:[{validation_id:'v2',validator_name:'uk-english',action:'warn',severity:'P1',passed:false,message:'hidden reasoning from model trace'}]}); expect(out.validator_rows[0].safe_summary).not.toMatch(/hidden reasoning/i); });
 it('missing data produces safe empty state',()=>{ const out=renderInternalQAReport({...input, public_report_v3:{...report,critical_component_gates:[],standout_delta:undefined}}); const sec=out.sections.find((s)=>s.section_id==='standout_delta'); expect(sec?.status).toBe('empty'); expect(sec?.safe_text[0]).toMatch(/No validated content/i); });
 it('GF-01 artefacts include rendered snapshot expectations',()=>{ const gf1=GOLDEN_FIXTURES.find((f)=>f.id==='GF-01')!; expect(gf1.later_artefacts).toContain('rendered QA snapshot'); });
 it('renderer metrics exist',()=>{ expect(getS5RendererMetricRegistry().length).toBeGreaterThan(5); });

 it('sanitise redacts hidden reasoning and chain of thought together',()=>{ const out=renderInternalQAReport({...input, validator_trace_summary:[{validation_id:'v3',validator_name:'uk-english',action:'warn',severity:'P1',passed:false,message:'hidden reasoning and chain of thought detected'}]}); expect(out.validator_rows[0].safe_summary).not.toMatch(/hidden reasoning|chain of thought/i); });
 it('sanitise redacts chain-of-thought and private_trace together',()=>{ const out=renderInternalQAReport({...input, validator_trace_summary:[{validation_id:'v4',validator_name:'uk-english',action:'warn',severity:'P1',passed:false,message:'chain-of-thought plus private_trace leaked'}]}); expect(out.validator_rows[0].safe_summary).not.toMatch(/chain-of-thought|private_trace/i); });
 it('safe text remains unchanged',()=>{ const out=renderInternalQAReport({...input, validator_trace_summary:[{validation_id:'v5',validator_name:'uk-english',action:'pass',severity:'P2',passed:true,message:'Clean safe summary'}]}); expect(out.validator_rows[0].safe_summary).toBe('Clean safe summary'); });
 it('assertNoPrivateTraceRendered fails if forbidden text is manually present',()=>{ expect(()=>assertNoPrivateTraceRendered({ trace_rows:[], sections:[{ section_id:'x', title:'x', status:'ok', safe_text:['hidden reasoning'], linked_claim_ids:[], validator_statuses:[] }], validator_rows:[] })).toThrow(); });
});
