import type { S10OperatorAssumptionCheckpoint, S10OperatorExpectation } from "@/lib/audition-rules";

export const s10CanaryAOperatorFacts = {
  fixture_id: "s10-canary-a-incomplete-mandatory-package",
  selected_level: "professional",
  supplied_brief: [
    "Project: Canary A MT package.",
    "Role: performer.",
    "Please prepare Side 1, pages 85-87.",
    "Please include a contemporary legit musical-theatre song.",
    "Submit one continuous landscape video, close-up/head-and-shoulders framing.",
    "Upload one file only, named LASTNAME_FIRSTNAME_CANARYA.mp4, by the stated deadline.",
  ].join("\n"),
  operator_observed_tape_facts: {
    sequence: ["intro first", "partial song present", "tape cuts off before package is complete"],
    side_1: "absent",
    song: "partially_present",
    song_completion: "cut_off",
    package: "incomplete",
    audio_assessable: true,
    video_assessable: true,
    framing_assessable: true,
  },
} as const;

export const s10CanaryALegacyFalsePositiveRawReport = {
  audition_type: "musical_theatre",
  overall_score: 93,
  overall_score_final: 93,
  headline: "Strong for this level",
  casting_headline: "Strong for this level",
  verdict: "Strong for this level",
  verdict_final: "Strong for this level",
  casting_insight: "well aligned with the supplied brief",
  scores: {
    technical: 92,
    audio: 88,
    vocal: 94,
    acting: 91,
    brief_adherence: 90,
    professional_presentation: 93,
  },
  brief_adherence_breakdown: {
    material_compliance: 100,
    note: "Correct material, orientation, and framing.",
  },
  detected_components: [
    { type: "acting_scene", score: 92, note: "Naturalistic acting with good pace" },
    { type: "song", score: 94, note: "Strong contemporary legit vocal with clear storytelling" },
  ],
  strengths: [
    { point: "Correct material, orientation, and framing" },
    { point: "Single-file submission as requested" },
    { point: "The easy-going warmth and wit are very present." },
  ],
  improvements: [{ point: "Correct the file naming convention" }],
  coaching_drills: ["Use one pass to strengthen blocked material."],
  fix_first: "Correct the file naming convention",
  priority_fixes: [{ headline: "Correct the file naming convention" }],
  category_rationale: {
    acting: { what_works: "Naturalistic acting with good pace" },
    vocal: { what_works: "Strong contemporary legit vocal with clear storytelling" },
    brief_adherence: { what_works: "Correct material, orientation, and framing" },
  },
  timestamped_notes: [
    { timestamp: "00:05", note: "Strong start to the scene" },
    { timestamp: "00:25", note: "Good use of eyeline" },
    { timestamp: "00:55", note: "transition into the song" },
    { timestamp: "01:35", note: "Excellent vocal control on the sustained notes" },
  ],
  presentation_notes: ["Single-file submission as requested"],
} as const;

export const s10CanaryABriefContext = {
  project_name: "Canary A MT package",
  role_name: "performer",
  discipline: "musical_theatre",
  audition_type: "self_tape",
  material_package_summary:
    "Professional MT self-tape package requiring Side 1 plus a contemporary legit song.",
  role_description_summary: "Role context preserved for report context, not treated as material.",
  deadline_summary: "Brief includes deadline/upload instructions.",
  upload_summary: "Upload one file only.",
  file_naming_summary: "Use LASTNAME_FIRSTNAME_CANARYA.mp4.",
} as const;

export const s10CanaryABriefRequirements = [
  {
    id: "req-side-1",
    brief_text: "Please prepare Side 1, pages 85-87.",
    summary: "Required Side 1 acting scene",
    category: "material",
    importance: "mandatory",
    expected_evidence_in_tape: "The submitted tape contains the requested Side 1 acting scene.",
    achievement_test: "Side 1 is present and complete in the submitted tape.",
    submission_impact_if_missing: "Mandatory acting material is missing.",
    report_destination: "brief_achievement",
    confidence: "high",
  },
  {
    id: "req-song",
    brief_text: "Please include a contemporary legit musical-theatre song.",
    summary: "Contemporary legit MT song",
    category: "material",
    importance: "mandatory",
    expected_evidence_in_tape:
      "The submitted tape contains the song and it runs through to the end.",
    achievement_test: "Song is present and complete.",
    submission_impact_if_missing: "Mandatory song material is missing or incomplete.",
    report_destination: "brief_achievement",
    confidence: "high",
  },
  {
    id: "req-continuous-video",
    brief_text: "Submit one continuous video.",
    summary: "One continuous video containing the full package",
    category: "admin_process",
    importance: "mandatory",
    expected_evidence_in_tape: "Side 1 and song appear in one continuous final video.",
    achievement_test: "All required material appears in the same continuous tape.",
    submission_impact_if_missing: "Package is incomplete.",
    report_destination: "brief_achievement",
    confidence: "high",
  },
  {
    id: "req-one-file",
    brief_text: "Upload one file only.",
    summary: "One final checked file",
    category: "admin_process",
    importance: "mandatory",
    expected_evidence_in_tape: "Final export contains all required material.",
    achievement_test: "One final file contains Side 1 and song.",
    submission_impact_if_missing: "Final package requires checking before upload.",
    report_destination: "next_action",
    confidence: "high",
  },
  {
    id: "req-landscape-framing",
    brief_text: "Use landscape orientation and close-up/head-and-shoulders framing.",
    summary: "Landscape close-up/head-and-shoulders framing",
    category: "technical",
    importance: "mandatory",
    expected_evidence_in_tape: "Video is landscape and framed close-up/head-and-shoulders.",
    achievement_test: "Framing/orientation are assessable and match the brief.",
    submission_impact_if_missing: "Technical presentation risk if not followed.",
    report_destination: "presentation_notes",
    confidence: "high",
  },
  {
    id: "req-file-name",
    brief_text: "Name the file LASTNAME_FIRSTNAME_CANARYA.mp4.",
    summary: "File naming instruction",
    category: "admin_process",
    importance: "mandatory",
    expected_evidence_in_tape: "Not directly visible in the tape; final upload check required.",
    achievement_test: "Filename is checked before upload.",
    submission_impact_if_missing: "Admin final check issue, not performance criticism.",
    report_destination: "next_action",
    confidence: "medium",
  },
  {
    id: "ctx-role",
    brief_text: "Role: performer.",
    summary: "Role context",
    category: "role_context",
    importance: "ambiguous",
    expected_evidence_in_tape:
      "Role context informs judgement but is not separate required material.",
    achievement_test: "Preserved as context.",
    submission_impact_if_missing: "No direct material blocker.",
    report_destination: "brief_context",
    confidence: "medium",
  },
] as const;

export const s10CanaryAObservedTapeSequence = [
  {
    id: "seq-intro",
    label: "Intro first",
    component_type: "ident",
    linked_requirement_ids: [],
    start_time: null,
    end_time: null,
    present_status: "present",
    completion_status: "not_applicable",
    evidence_summary: "The submitted tape starts with an intro before the song portion.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    confidence: "medium",
    assessability_notes: "Intro is observable.",
  },
  {
    id: "seq-song",
    label: "Observed song section",
    component_type: "song",
    linked_requirement_ids: ["req-song"],
    start_time: null,
    end_time: null,
    present_status: "partially_present",
    completion_status: "cut_off",
    evidence_summary: "A song portion is present, but completion is cut off or not confirmed.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    confidence: "medium",
    assessability_notes: "Audio is assessable for the observed portion.",
  },
] as const;

export const s10CanaryAComponentVerifications = [
  {
    requirement_id: "req-side-1",
    requirement_summary: "Required Side 1 acting scene",
    observed_status: "absent",
    completion_status: "incomplete",
    evidence_summary: "The required Side 1 acting scene was not identified in the submitted tape.",
    observed_from_media: false,
    evidence_basis: "uncertainty",
    timestamp_refs: [],
    confidence: "high",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-song",
    requirement_summary: "Contemporary legit MT song",
    observed_status: "partially_present",
    completion_status: "cut_off",
    evidence_summary:
      "Only the observed song portion is available; song completion is not confirmed.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    timestamp_refs: [],
    confidence: "medium",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-continuous-video",
    requirement_summary: "One continuous video containing the full package",
    observed_status: "partially_present",
    completion_status: "incomplete",
    evidence_summary:
      "Continuity may be assessable, but the required material package is incomplete because Side 1 is missing and song completion is not confirmed.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    timestamp_refs: [],
    confidence: "medium",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-one-file",
    requirement_summary: "One final checked file",
    observed_status: "not_assessable",
    completion_status: "not_applicable",
    evidence_summary: "Final upload file status is not assessable from the observed tape.",
    observed_from_media: false,
    evidence_basis: "deterministic_metadata",
    timestamp_refs: [],
    confidence: "medium",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-landscape-framing",
    requirement_summary: "Landscape close-up/head-and-shoulders framing",
    observed_status: "present",
    completion_status: "complete",
    evidence_summary: "Framing/orientation are assessable in the submitted tape.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    timestamp_refs: [],
    confidence: "high",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-file-name",
    requirement_summary: "File naming instruction",
    observed_status: "not_assessable",
    completion_status: "not_applicable",
    evidence_summary: "Filename must be checked at export/upload.",
    observed_from_media: false,
    evidence_basis: "deterministic_metadata",
    timestamp_refs: [],
    confidence: "medium",
    cannot_infer_from_brief_only: true,
  },
] as const;

export const s10CanaryAMediaObservationSummary = {
  audio_assessable: true,
  video_assessable: true,
  framing_assessable: true,
  continuity_assessable: true,
  abrupt_cutoff_detected: true,
  one_continuous_video_observed: true,
  duration_summary: "Short incomplete package: intro plus partial/cut-off song only.",
  uncertainties: ["Song completion is not confirmed; required Side 1 was not identified."],
} as const;

const requirementResult = (
  requirement_id: string,
  requirement_summary: string,
  category: string,
  importance: string,
  observed_status: string,
  completion_status: string,
  achievement_status: string,
  evidence_summary: string,
  submission_impact: string,
  fix_category: string,
  recommended_action: string,
) => ({
  requirement_id,
  requirement_summary,
  category,
  importance,
  observed_status,
  completion_status,
  achievement_status,
  evidence_summary,
  submission_impact,
  fix_category,
  recommended_action,
  confidence: "high",
  linked_observed_sequence_ids: requirement_id === "req-song" ? ["seq-song"] : [],
  linked_component_verification_ids: [`cv-${requirement_id.replace("req-", "")}`],
  cannot_infer_from_brief_only: true,
});

export const s10CanaryAExpectedModules = {
  brief_context: s10CanaryABriefContext,
  brief_requirements: s10CanaryABriefRequirements,
  observed_tape_sequence: s10CanaryAObservedTapeSequence,
  component_verifications: s10CanaryAComponentVerifications,
  media_observation_summary: s10CanaryAMediaObservationSummary,
  brief_achievement_matrix: {
    overall_status: "not_achieved",
    mandatory_status: "blocked",
    readiness_impact: "submission_blocker",
    summary: "The required Side 1 was not observed and the song/final package is incomplete.",
    achieved_requirements: ["Landscape close-up/head-and-shoulders framing"],
    missing_or_incomplete_requirements: [
      "Required Side 1 acting scene",
      "Contemporary legit MT song completion",
      "One continuous video containing the full package",
    ],
    not_assessable_requirements: [],
    final_check_requirements: ["One final checked file", "File naming instruction"],
    requirement_results: [
      requirementResult(
        "req-side-1",
        "Required Side 1 acting scene",
        "material",
        "mandatory",
        "absent",
        "incomplete",
        "not_achieved",
        "The required Side 1 acting scene was not identified in the submitted tape.",
        "submission_blocker",
        "must_fix",
        "Record and include the full required Side 1 acting scene.",
      ),
      requirementResult(
        "req-song",
        "Contemporary legit MT song",
        "material",
        "mandatory",
        "partially_present",
        "cut_off",
        "partly_achieved",
        "Only the observed song portion is available; song completion is not confirmed.",
        "material_gap",
        "must_fix",
        "Confirm the song runs through to the end in the final take.",
      ),
      requirementResult(
        "req-continuous-video",
        "One continuous video containing the full package",
        "admin_process",
        "mandatory",
        "partially_present",
        "incomplete",
        "partly_achieved",
        "The continuous-video package is incomplete because required material is missing.",
        "material_gap",
        "must_fix",
        "Check Side 1 and song are both present in one continuous final video.",
      ),
      requirementResult(
        "req-one-file",
        "One final checked file",
        "admin_process",
        "mandatory",
        "not_assessable",
        "not_applicable",
        "not_assessable",
        "Final file status requires export/upload checking after the retake.",
        "final_check",
        "final_check",
        "Export one final checked file containing Side 1 and song.",
      ),
      requirementResult(
        "req-landscape-framing",
        "Landscape close-up/head-and-shoulders framing",
        "technical",
        "mandatory",
        "present",
        "complete",
        "achieved",
        "Audio/framing are assessable and do not create the blocker.",
        "supports_submission",
        "preserve",
        "Keep the assessable framing while fixing missing material.",
      ),
      requirementResult(
        "req-file-name",
        "File naming instruction",
        "admin_process",
        "mandatory",
        "not_assessable",
        "not_applicable",
        "not_assessable",
        "Filename is a final upload check, not the first performance fix.",
        "final_check",
        "final_check",
        "Check the filename after exporting the complete final package.",
      ),
    ],
  },
  readiness_score_judgement: {
    decision: "retake_required_if_possible",
    headline: "Retake required if possible: the required Side 1 is missing.",
    rationale: [
      "The mandatory Side 1 acting scene was not observed.",
      "The song/package is incomplete, so visible strengths do not make the submission ready.",
    ],
    confidence: "high",
    performance_quality_score: 78,
    brief_completion_score: 25,
    overall_submission_readiness_score: 42,
    score_band_label: "retake_required_if_possible",
    score_explanation:
      "The visible score reflects submission readiness: missing Side 1 and incomplete song/package block the professional package.",
    brief_blocker_override: true,
    performance_quality_summary: "Observed song/audio evidence may contain useful strengths.",
    brief_completion_summary: "Mandatory material is missing or incomplete.",
    technical_assessability_summary: "Audio/framing are assessable and may be preserved.",
    selected_level_calibration_summary:
      "At professional level, a package missing required Side 1 is not submit-ready.",
    professional_nuance_summary:
      "Fix the mandatory package before optional polish or admin details.",
    category_scores: [
      {
        category_id: "brief_adherence",
        score: 25,
        score_basis: "Required Side 1 is missing and song/package completion is not confirmed.",
        what_works: "",
        why_not_full_score: "Mandatory material is incomplete.",
        close_gap: "Record Side 1 and complete the song/final package.",
        confidence: "high",
        blocked_or_not_assessable_reason: null,
      },
      {
        category_id: "audio",
        score: 86,
        score_basis: "Audio is assessable for the observed portion.",
        what_works: "Audio/framing can be preserved.",
        why_not_full_score: "",
        close_gap: "",
        confidence: "high",
        blocked_or_not_assessable_reason: null,
      },
      {
        category_id: "technical",
        score: 82,
        score_basis: "Framing/orientation are assessable; package content remains incomplete.",
        what_works: "Framing is usable.",
        why_not_full_score: "Package completion is still missing.",
        close_gap: "Retake with Side 1 and complete song in final file.",
        confidence: "medium",
        blocked_or_not_assessable_reason: null,
      },
    ],
    category_rationale: {},
    component_scores: [
      {
        component_type: "acting_scene",
        linked_requirement_ids: ["req-side-1"],
        observed_status: "absent",
        completion_status: "incomplete",
        score: null,
        score_basis: "Required Side 1 was not observed.",
        confidence: "high",
        cannot_score_reason:
          "Acting scene is not assessable because the required Side 1 is absent.",
      },
      {
        component_type: "song",
        linked_requirement_ids: ["req-song"],
        observed_status: "partially_present",
        completion_status: "cut_off",
        score: 72,
        score_basis: "Score is limited to the observed song portion only.",
        confidence: "medium",
        cannot_score_reason: null,
      },
    ],
    component_score_notes: [
      "Acting-scene score is unavailable because the required Side 1 is absent.",
      "Song score applies only to the observed portion.",
    ],
    score_contradiction_warnings: [
      {
        affected_field: "overall_score",
        original_value: 93,
        capped_value: 42,
        matrix_reason: "Mandatory Side 1 missing.",
        source: "legacy_raw_report",
      },
    ],
    repair_prompt_status: "classified_contradictory",
  },
} as const;

const fixItem = (id: string, title: string, exact_action: string, urgency = "high") => ({
  id,
  title,
  issue: title,
  why_it_matters: "This follows from the S10 brief achievement matrix.",
  exact_action,
  source_category: "brief",
  urgency,
  submission_impact: id === "fix-side-1" ? "submission_blocker" : "material_gap",
  linked_requirement_ids: [id === "fix-side-1" ? "req-side-1" : "req-song"],
  linked_matrix_result_ids: [id === "fix-side-1" ? "req-side-1" : "req-song"],
  linked_component_verification_ids: [id === "fix-side-1" ? "cv-side-1" : "cv-song"],
  linked_readiness_reason_ids: [],
  evidence_summary: exact_action,
  confidence: "high",
  is_fix_first_candidate: id === "fix-side-1",
  is_generic_fallback: false,
  source_authority: "s10_ai_authored",
  legacy_source_used: false,
});

export const s10CanaryAExpectedReportModules = {
  ...s10CanaryAExpectedModules,
  s10_fix_hierarchy: {
    fix_first: fixItem(
      "fix-side-1",
      "Record/include the full required Side 1 acting scene.",
      "Record the full required Side 1 and include it in the final continuous video.",
      "critical_gap",
    ),
    priority_fixes: [],
    must_fix_before_submitting: [
      fixItem(
        "fix-side-1",
        "Record/include the full required Side 1 acting scene.",
        "Record the full required Side 1 and include it in the final continuous video.",
        "critical_gap",
      ),
      fixItem(
        "fix-song",
        "Complete or confirm the song runs through to the end.",
        "Retake or playback-check the song so completion is confirmed.",
      ),
      fixItem(
        "fix-package",
        "Check Side 1 and song are both present in one continuous final video.",
        "Export a final package containing both mandatory materials.",
      ),
    ],
    should_improve_if_retaking: [],
    optional_polish: [],
    preserve: [
      {
        ...fixItem(
          "preserve-audio",
          "Preserve assessable audio/framing.",
          "Keep audio/framing stable while fixing missing material.",
          "low",
        ),
        source_category: "technical",
        submission_impact: "supports_submission",
        is_fix_first_candidate: false,
      },
    ],
    do_not_overfix: [
      {
        ...fixItem(
          "do-not-overfix-audio",
          "Do not chase audio/framing changes before missing material.",
          "Prioritise Side 1 and package completion first.",
          "low",
        ),
        source_category: "technical",
        submission_impact: "supports_submission",
        is_fix_first_candidate: false,
      },
    ],
    action_contradiction_warnings: [],
  },
  s10_next_action_plan: {
    submit_checklist: [],
    retake_plan: [
      "Record the full required Side 1 acting scene.",
      "Confirm the song runs through to the end.",
      "Check Side 1 and song are both present in one continuous final video.",
    ],
    final_checks: [
      "Export one final checked file containing Side 1 and song.",
      "Check the requested file naming convention after export.",
    ],
    playback_checks: ["Playback-check the end of the song for cut-off before upload."],
    do_not_overfix: [
      "Do not chase audio/framing if already assessable; prioritise missing material.",
    ],
    if_time_is_short_guidance: [],
    no_retake_needed_reason: null,
    confidence: "high",
  },
  s10_professional_critique: {
    summary:
      "There may be useful audio/framing and observed song evidence, but the package is incomplete.",
    performance_strengths: [],
    brief_package_strengths: [],
    technical_presentation_strengths: [
      {
        id: "strength-audio-framing",
        title: "Audio/framing are assessable.",
        detail: "Keep the current clarity while retaking the missing material.",
        why_it_matters: "It lets the panel hear and see the observed portion clearly enough.",
        evidence_summary: "Audio/framing assessability was supported.",
        source_category: "technical",
        linked_requirement_ids: ["req-landscape-framing"],
        linked_component_verification_ids: ["cv-landscape-framing"],
        linked_matrix_result_ids: ["req-landscape-framing"],
        linked_readiness_reason_ids: [],
        linked_fix_ids: [],
        confidence: "high",
        is_component_verified: true,
        component_status: "present",
        applies_to_observed_portion_only: false,
        is_generic_fallback: false,
      },
    ],
    vocal_or_singing_strengths: [
      {
        id: "strength-song-observed-portion",
        title: "Observed song portion is assessable.",
        detail: "Any song note applies only to the observed portion; completion is not confirmed.",
        why_it_matters: "This preserves useful evidence without implying package readiness.",
        evidence_summary: "Song is partially present and cut off/unconfirmed.",
        source_category: "vocal",
        linked_requirement_ids: ["req-song"],
        linked_component_verification_ids: ["cv-song"],
        linked_matrix_result_ids: ["req-song"],
        linked_readiness_reason_ids: [],
        linked_fix_ids: [],
        confidence: "medium",
        is_component_verified: true,
        component_status: "partially_present",
        applies_to_observed_portion_only: true,
        is_generic_fallback: false,
      },
    ],
    acting_strengths: [],
    movement_or_physical_strengths: [],
    professional_presentation_notes: [],
    preserve: [
      {
        id: "preserve-audio-framing",
        title: "Preserve assessable audio/framing.",
        detail: "Keep the technical setup stable while fixing Side 1 and song completion.",
        evidence_summary: "Audio/framing assessable.",
        why_to_preserve: "The blocker is missing material, not audio/framing.",
        linked_component_verification_ids: ["cv-landscape-framing"],
        confidence: "high",
        is_generic_fallback: false,
      },
    ],
    do_not_overfix: [
      {
        id: "do-not-overfix-audio",
        title: "Do not overfix audio/framing first.",
        detail: "Prioritise the missing Side 1 and incomplete package.",
        evidence_summary: "Audio/framing are assessable.",
        why_to_preserve: "Audio/framing positives must not outrank missing mandatory material.",
        linked_component_verification_ids: ["cv-landscape-framing"],
        confidence: "high",
        is_generic_fallback: false,
      },
    ],
    critique_limitations: ["Acting-scene strengths cannot be assessed because Side 1 is absent."],
    contradiction_warnings: [],
  },
  s10_technique_commentary: {
    summary: "Technique notes are limited by the missing required Side 1.",
    acting: {
      status: "not_assessable",
      headline: "Acting scene not assessable because required Side 1 is missing.",
      observations: [],
      what_is_working: [],
      what_could_improve: [],
      practical_actions: ["Record the required Side 1 before judging acting technique."],
      preserve: [],
      not_assessable_reason: "The required Side 1 was not identified in the submitted tape.",
      confidence: "high",
    },
    vocal_singing: {
      status: "partially_assessable",
      headline: "Song technique applies only to the observed portion.",
      observations: [],
      what_is_working: ["Observed song portion is assessable but completion is not confirmed."],
      what_could_improve: ["Confirm the song runs through to the end."],
      practical_actions: ["Playback-check or retake the song so the ending is complete."],
      preserve: [],
      not_assessable_reason: null,
      confidence: "medium",
    },
    movement_dance: {
      status: "not_applicable",
      headline: "Movement/dance was not required or visible.",
      observations: [],
      what_is_working: [],
      what_could_improve: [],
      practical_actions: [],
      preserve: [],
      not_assessable_reason: null,
      confidence: "medium",
    },
    musical_theatre_package: {
      status: "partially_assessable",
      headline: "The MT package is incomplete because Side 1 is missing.",
      observations: [],
      what_is_working: [],
      what_could_improve: ["Complete the Side 1 plus song package before polish."],
      practical_actions: ["Record Side 1 and confirm the song ending in one final video."],
      preserve: [],
      not_assessable_reason: null,
      confidence: "high",
    },
    self_tape_presentation: {
      status: "assessable",
      headline: "Audio/framing can be preserved while fixing material.",
      observations: [],
      what_is_working: ["Audio/framing are assessable."],
      what_could_improve: [],
      practical_actions: [],
      preserve: ["Keep audio/framing stable."],
      not_assessable_reason: null,
      confidence: "high",
    },
    commercial_screen_task: {
      status: "not_applicable",
      headline: "",
      observations: [],
      what_is_working: [],
      what_could_improve: [],
      practical_actions: [],
      preserve: [],
      not_assessable_reason: null,
      confidence: "low",
    },
    limitations: [],
    contradiction_warnings: [],
  },
  s10_timestamped_commentary: {
    summary: "No acting-scene timestamp is available because Side 1 was not observed.",
    notes: [
      {
        id: "note-side-1-missing",
        timecode: null,
        start_time: null,
        end_time: null,
        time_band_label: null,
        display_label: "Not observed",
        timestamp_precision: "unavailable",
        section: "missing_component",
        title: "Required Side 1 not observed.",
        detail: "The required acting scene was not identified in this tape.",
        action: "Record and include Side 1.",
        evidence_summary: "Component verification marked Side 1 absent.",
        linked_requirement_ids: ["req-side-1"],
        linked_observed_sequence_ids: [],
        linked_component_verification_ids: ["cv-side-1"],
        linked_matrix_result_ids: ["req-side-1"],
        linked_fix_ids: ["fix-side-1"],
        linked_strength_ids: [],
        linked_technique_observation_ids: [],
        component_type: "acting_scene",
        component_status: "absent",
        applies_to_observed_portion_only: false,
        is_exact_timestamp_supported: false,
        is_legacy_timestamp_projection: false,
        note_source_authority: "s10_ai_authored",
        legacy_source_used: false,
        is_missing_component_note: true,
        is_projection_safe: false,
        confidence: "high",
        is_generic_fallback: false,
      },
      {
        id: "note-song-observed-portion",
        timecode: null,
        start_time: null,
        end_time: null,
        time_band_label: "Observed song section",
        display_label: "Observed song section",
        timestamp_precision: "order_only",
        section: "technique",
        title: "Song notes apply only to the observed portion.",
        detail: "Song completion is not confirmed, so do not treat this as package-ready.",
        action: "Playback-check the end of the song for cut-off.",
        evidence_summary: "Song is partially present and cut off/unconfirmed.",
        linked_requirement_ids: ["req-song"],
        linked_observed_sequence_ids: ["seq-song"],
        linked_component_verification_ids: ["cv-song"],
        linked_matrix_result_ids: ["req-song"],
        linked_fix_ids: ["fix-song"],
        linked_strength_ids: ["strength-song-observed-portion"],
        linked_technique_observation_ids: [],
        component_type: "song",
        component_status: "partially_present",
        applies_to_observed_portion_only: true,
        is_exact_timestamp_supported: false,
        is_legacy_timestamp_projection: false,
        note_source_authority: "s10_ai_authored",
        legacy_source_used: false,
        is_missing_component_note: false,
        is_projection_safe: false,
        confidence: "medium",
        is_generic_fallback: false,
      },
    ],
    component_ranges: [],
    missing_or_unobserved_components: ["Required Side 1 acting scene"],
    timestamp_limitations: [
      "Exact acting-scene timestamps are unavailable because the scene was not observed.",
    ],
    projection_notes: [],
    legacy_projection_blocked_count: 4,
    exact_timestamp_supported_count: 0,
    time_banded_note_count: 0,
    order_only_note_count: 1,
    missing_component_note_count: 1,
    contradiction_warnings: [],
  },
} as const;

export const s10CanaryAExpectedViewModel = {
  required_authoritative_sections: [
    "readiness_header",
    "submission_guidance",
    "score_summary",
    "brief_achievement",
    "observed_tape",
    "component_breakdown",
    "fix_hierarchy",
    "next_action_plan",
    "strengths_and_preserve",
    "technique_commentary",
    "timestamped_commentary",
  ],
  allowed_route_content: [
    "Retake required if possible",
    "required Side 1",
    "not observed",
    "not achieved",
    "song completion",
    "completion is not confirmed",
    "partial",
    "continuous final video",
    "final package",
    "Playback-check",
    "Acting scene not assessable",
    "Audio/framing are assessable",
  ],
  forbidden_route_content: [
    "Take 1 · 93",
    "Strong for this level",
    "well aligned with the supplied brief",
    "Correct material",
    "Single-file submission as requested",
    "Naturalistic acting with good pace",
    "easy-going warmth and wit are very present",
    "Strong contemporary legit vocal with clear storytelling",
    "00:05 Strong start to the scene",
    "00:25 Good use of eyeline",
    "good use of eyeline",
    "scene partner",
    "This affects readability, not talent",
    "Blocked: a major casting brief instruction wasn't followed",
    "Blocked: a major casting brief instruction wasn’t followed",
    "No single public-safe priority fix was available",
    "complete song package",
  ],
} as const;

export const s10CanaryAOperatorAssumptionCheckpoint = {
  checkpoint_id: "s10-canary-a-operator-checkpoint",
  fixture_id: s10CanaryAOperatorFacts.fixture_id,
  take_id: "canary-a-take",
  audition_id: "canary-a-audition",
  report_context: "S10 deterministic incomplete mandatory package fixture",
  declared_fixture_type: "incomplete_mandatory_package",
  declared_expected_outcome: "Retake required because required Side 1 is missing.",
  same_brief_confirmed: true,
  same_video_confirmed: true,
  same_media_identity: "confirmed",
  rerun_intent: "not_applicable",
  strong_complete_take_confirmed: false,
  incomplete_mandatory_package_confirmed: true,
  expected_primary_blocker: "Missing required Side 1",
  expected_secondary_notes: [
    "Partial/incomplete song",
    "Song completion not confirmed",
    "Final continuous one-file check required",
  ],
  score_chips_intentionally_visible: true,
  comparison_chips_intentionally_visible: false,
  comparison_context: null,
  changed_brief_confirmed: false,
  changed_level_confirmed: false,
  changed_report_version_confirmed: false,
  operator_notes: [
    "Operator-declared fixture facts are deterministic and must not be inferred from raw_report.",
  ],
  created_by_role: "test",
  created_at: "2026-05-24T00:00:00.000Z",
  confidence: "confirmed",
  scope: "deterministic_fixture",
} satisfies S10OperatorAssumptionCheckpoint;

export const s10CanaryAOperatorExpectation = {
  expected_recommendation: "retake_required_if_possible",
  expected_brief_achievement_status: "not_achieved",
  expected_missing_requirements: ["req-side-1", "req-song"],
  expected_present_requirements: [],
  expected_not_assessable_areas: ["acting"],
  expected_fix_first: "Side 1",
  expected_score_band: "retake_required_if_possible",
  expected_same_video_status: null,
  expected_comparison_policy: null,
  expected_forbidden_phrases: s10CanaryAExpectedViewModel.forbidden_route_content.slice(),
  expected_required_phrases: [
    "Retake required if possible",
    "required Side 1|Side 1 not observed|required acting side not identified",
    "Record/include the full required Side 1 acting scene|record Side 1",
  ],
} satisfies S10OperatorExpectation;

export function buildS10CanaryAReportInput() {
  return {
    ...structuredClone(s10CanaryALegacyFalsePositiveRawReport),
    brief_context: structuredClone(s10CanaryAExpectedReportModules.brief_context),
    brief_requirements: structuredClone(s10CanaryAExpectedReportModules.brief_requirements),
    observed_tape_sequence: structuredClone(s10CanaryAExpectedReportModules.observed_tape_sequence),
    component_verifications: structuredClone(
      s10CanaryAExpectedReportModules.component_verifications,
    ),
    media_observation_summary: structuredClone(
      s10CanaryAExpectedReportModules.media_observation_summary,
    ),
    brief_achievement_matrix: structuredClone(
      s10CanaryAExpectedReportModules.brief_achievement_matrix,
    ),
    readiness_score_judgement: structuredClone(
      s10CanaryAExpectedReportModules.readiness_score_judgement,
    ),
    s10_fix_hierarchy: structuredClone(s10CanaryAExpectedReportModules.s10_fix_hierarchy),
    s10_next_action_plan: structuredClone(s10CanaryAExpectedReportModules.s10_next_action_plan),
    s10_professional_critique: structuredClone(
      s10CanaryAExpectedReportModules.s10_professional_critique,
    ),
    s10_technique_commentary: structuredClone(
      s10CanaryAExpectedReportModules.s10_technique_commentary,
    ),
    s10_timestamped_commentary: structuredClone(
      s10CanaryAExpectedReportModules.s10_timestamped_commentary,
    ),
  };
}

export function buildS10CanaryAViewContext() {
  return {
    briefContext: structuredClone(s10CanaryAExpectedReportModules.brief_context),
    briefRequirements: structuredClone(s10CanaryAExpectedReportModules.brief_requirements),
    observedTapeSequence: structuredClone(s10CanaryAExpectedReportModules.observed_tape_sequence),
    componentVerifications: structuredClone(
      s10CanaryAExpectedReportModules.component_verifications,
    ),
    mediaObservationSummary: structuredClone(
      s10CanaryAExpectedReportModules.media_observation_summary,
    ),
  };
}
