export const s10StrongCompleteProfessionalOperatorFacts = {
  fixture_id: "s10-strong-complete-professional",
  selected_level: "professional",
  supplied_brief: [
    "Project: Strong Complete MT package.",
    "Role: performer.",
    "Please prepare Side 1, pages 85-87.",
    "Please include a contemporary legit musical-theatre song.",
    "Submit one continuous landscape video, close-up/head-and-shoulders framing.",
    "Upload one file only, named LASTNAME_FIRSTNAME_STRONG.mp4, by the stated deadline.",
  ].join("\n"),
  operator_observed_tape_facts: {
    sequence: ["intro first", "complete Side 1 acting scene", "complete song"],
    side_1: "present",
    song: "present",
    song_completion: "complete",
    package: "complete",
    audio_assessable: true,
    video_assessable: true,
    framing_assessable: true,
    abrupt_cutoff_affecting_required_material: false,
  },
} as const;

export const s10StrongCompleteProfessionalLegacySnapshot = {
  audition_type: "musical_theatre",
  overall_score: 96,
  overall_score_final: 96,
  headline: "Submit",
  casting_headline: "Submit",
  verdict: "Submit",
  verdict_final: "Submit",
  casting_insight: "Strong choices.",
  scores: {
    technical: 91,
    audio: 90,
    vocal: 94,
    acting: 93,
    brief_adherence: 96,
    professional_presentation: 92,
  },
  brief_adherence_breakdown: {
    material_compliance: 100,
    note: "Material appears complete.",
  },
  detected_components: [
    { type: "acting_scene", score: 93, note: "Strong choices." },
    { type: "song", score: 94, note: "Professional presentation." },
  ],
  strengths: [{ point: "Strong choices." }],
  improvements: [],
  coaching_drills: [],
  fix_first: null,
  priority_fixes: [],
  category_rationale: {
    acting: { what_works: "Strong choices." },
    vocal: { what_works: "Professional presentation." },
  },
  timestamped_notes: [],
  presentation_notes: ["Professional presentation."],
} as const;

export const s10StrongCompleteProfessionalBriefContext = {
  project_name: "Strong Complete MT package",
  role_name: "performer",
  discipline: "musical_theatre",
  audition_type: "self_tape",
  material_package_summary:
    "Professional MT self-tape package requiring Side 1 plus a contemporary legit song.",
  role_description_summary: "Role context preserved for report context.",
  deadline_summary: "Brief includes deadline/upload instructions.",
  upload_summary: "Upload one file only.",
  file_naming_summary: "Use LASTNAME_FIRSTNAME_STRONG.mp4.",
} as const;

export const s10StrongCompleteProfessionalBriefRequirements = [
  {
    id: "req-side-1",
    brief_text: "Please prepare Side 1, pages 85-87.",
    summary: "Required Side 1 acting scene",
    category: "material",
    importance: "mandatory",
    expected_evidence_in_tape: "The submitted tape contains the requested Side 1 acting scene.",
    achievement_test: "Side 1 is present and complete in the submitted tape.",
    submission_impact_if_missing: "Mandatory acting material is missing.",
    report_destination: "brief_achievement",
    confidence: "high",
  },
  {
    id: "req-song",
    brief_text: "Please include a contemporary legit musical-theatre song.",
    summary: "Contemporary legit MT song",
    category: "material",
    importance: "mandatory",
    expected_evidence_in_tape:
      "The submitted tape contains the song and it runs through to the end.",
    achievement_test: "Song is present and complete.",
    submission_impact_if_missing: "Mandatory song material is missing or incomplete.",
    report_destination: "brief_achievement",
    confidence: "high",
  },
  {
    id: "req-continuous-video",
    brief_text: "Submit one continuous video.",
    summary: "One continuous video containing the full package",
    category: "admin_process",
    importance: "mandatory",
    expected_evidence_in_tape: "Side 1 and song appear in one continuous final video.",
    achievement_test: "All required material appears in the same continuous tape.",
    submission_impact_if_missing: "Package is incomplete.",
    report_destination: "brief_achievement",
    confidence: "high",
  },
  {
    id: "req-one-file",
    brief_text: "Upload one file only.",
    summary: "One final checked file",
    category: "admin_process",
    importance: "mandatory",
    expected_evidence_in_tape: "Final export contains all required material.",
    achievement_test: "One final file contains Side 1 and song.",
    submission_impact_if_missing: "Final package requires checking before upload.",
    report_destination: "next_action",
    confidence: "high",
  },
  {
    id: "req-landscape-framing",
    brief_text: "Use landscape orientation and close-up/head-and-shoulders framing.",
    summary: "Landscape close-up/head-and-shoulders framing",
    category: "technical",
    importance: "mandatory",
    expected_evidence_in_tape: "Video is landscape and framed close-up/head-and-shoulders.",
    achievement_test: "Framing/orientation are assessable and match the brief.",
    submission_impact_if_missing: "Technical presentation risk if not followed.",
    report_destination: "presentation_notes",
    confidence: "high",
  },
  {
    id: "req-file-name",
    brief_text: "Name the file LASTNAME_FIRSTNAME_STRONG.mp4.",
    summary: "File naming instruction",
    category: "admin_process",
    importance: "mandatory",
    expected_evidence_in_tape: "Not directly visible in the tape; final upload check required.",
    achievement_test: "Filename is checked before upload.",
    submission_impact_if_missing: "Admin final check issue, not performance criticism.",
    report_destination: "next_action",
    confidence: "medium",
  },
  {
    id: "ctx-role",
    brief_text: "Role: performer.",
    summary: "Role context",
    category: "role_context",
    importance: "ambiguous",
    expected_evidence_in_tape:
      "Role context informs judgement but is not separate required material.",
    achievement_test: "Preserved as context.",
    submission_impact_if_missing: "No direct material blocker.",
    report_destination: "brief_context",
    confidence: "medium",
  },
] as const;

export const s10StrongCompleteProfessionalObservedTapeSequence = [
  {
    id: "seq-intro",
    label: "Intro first",
    component_type: "ident",
    linked_requirement_ids: [],
    start_time: "00:00",
    end_time: "00:06",
    present_status: "present",
    completion_status: "complete",
    evidence_summary: "The submitted tape starts with a brief ident before required material.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    confidence: "high",
    assessability_notes: "Intro is observable.",
  },
  {
    id: "seq-side-1",
    label: "Required Side 1 acting scene",
    component_type: "acting_scene",
    linked_requirement_ids: ["req-side-1"],
    start_time: "00:06",
    end_time: "01:04",
    present_status: "present",
    completion_status: "complete",
    evidence_summary: "The required Side 1 acting scene is present and complete.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    confidence: "high",
    assessability_notes: "Acting scene is assessable.",
  },
  {
    id: "seq-song",
    label: "Contemporary legit MT song",
    component_type: "song",
    linked_requirement_ids: ["req-song"],
    start_time: "01:05",
    end_time: "02:15",
    present_status: "present",
    completion_status: "complete",
    evidence_summary: "The song is present and runs through the ending.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    confidence: "high",
    assessability_notes: "Song is assessable through completion.",
  },
] as const;

export const s10StrongCompleteProfessionalComponentVerifications = [
  {
    requirement_id: "req-side-1",
    requirement_summary: "Required Side 1 acting scene",
    observed_status: "present",
    completion_status: "complete",
    evidence_summary: "The required Side 1 acting scene is present and complete.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    timestamp_refs: ["00:06-01:04"],
    confidence: "high",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-song",
    requirement_summary: "Contemporary legit MT song",
    observed_status: "present",
    completion_status: "complete",
    evidence_summary: "The contemporary legit MT song is present and complete.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    timestamp_refs: ["01:05-02:15"],
    confidence: "high",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-continuous-video",
    requirement_summary: "One continuous video containing the full package",
    observed_status: "present",
    completion_status: "complete",
    evidence_summary: "Side 1 and song appear in one continuous final video.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    timestamp_refs: ["00:00-02:15"],
    confidence: "high",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-one-file",
    requirement_summary: "One final checked file",
    observed_status: "not_assessable",
    completion_status: "not_applicable",
    evidence_summary:
      "Final upload file status is an admin final check; observed material package is complete.",
    observed_from_media: false,
    evidence_basis: "deterministic_metadata",
    timestamp_refs: [],
    confidence: "medium",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-landscape-framing",
    requirement_summary: "Landscape close-up/head-and-shoulders framing",
    observed_status: "present",
    completion_status: "complete",
    evidence_summary: "Framing/orientation are assessable and support submission.",
    observed_from_media: true,
    evidence_basis: "observed_audio_video",
    timestamp_refs: ["00:00-02:15"],
    confidence: "high",
    cannot_infer_from_brief_only: true,
  },
  {
    requirement_id: "req-file-name",
    requirement_summary: "File naming instruction",
    observed_status: "not_assessable",
    completion_status: "not_applicable",
    evidence_summary:
      "Filename remains a final upload check, not a performance or material blocker.",
    observed_from_media: false,
    evidence_basis: "deterministic_metadata",
    timestamp_refs: [],
    confidence: "medium",
    cannot_infer_from_brief_only: true,
  },
] as const;

export const s10StrongCompleteProfessionalMediaObservationSummary = {
  audio_assessable: true,
  video_assessable: true,
  framing_assessable: true,
  continuity_assessable: true,
  abrupt_cutoff_detected: false,
  one_continuous_video_observed: true,
  duration_summary: "Complete professional package: intro, Side 1, and complete song.",
  uncertainties: ["Filename and upload deadline remain final admin checks."],
} as const;

const requirementResult = (
  requirement_id: string,
  requirement_summary: string,
  category: string,
  importance: string,
  observed_status: string,
  completion_status: string,
  achievement_status: string,
  evidence_summary: string,
  submission_impact: string,
  fix_category: string,
  recommended_action: string,
) => ({
  requirement_id,
  requirement_summary,
  category,
  importance,
  observed_status,
  completion_status,
  achievement_status,
  evidence_summary,
  submission_impact,
  fix_category,
  recommended_action,
  confidence: "high",
  linked_observed_sequence_ids:
    requirement_id === "req-side-1"
      ? ["seq-side-1"]
      : requirement_id === "req-song"
        ? ["seq-song"]
        : [],
  linked_component_verification_ids: [`cv-${requirement_id.replace("req-", "")}`],
  cannot_infer_from_brief_only: true,
});

export const s10StrongCompleteProfessionalExpectedModules = {
  brief_context: s10StrongCompleteProfessionalBriefContext,
  brief_requirements: s10StrongCompleteProfessionalBriefRequirements,
  observed_tape_sequence: s10StrongCompleteProfessionalObservedTapeSequence,
  component_verifications: s10StrongCompleteProfessionalComponentVerifications,
  media_observation_summary: s10StrongCompleteProfessionalMediaObservationSummary,
  brief_achievement_matrix: {
    overall_status: "mostly_achieved",
    mandatory_status: "clear",
    readiness_impact: "supports_submission",
    summary:
      "Brief mostly achieved: Side 1, song, package continuity and framing are verified; filename/upload remain final admin checks.",
    achieved_requirements: [
      "Required Side 1 acting scene",
      "Contemporary legit MT song",
      "One continuous video containing the full package",
      "Landscape close-up/head-and-shoulders framing",
    ],
    missing_or_incomplete_requirements: [],
    not_assessable_requirements: [],
    final_check_requirements: ["One final checked file", "File naming instruction"],
    requirement_results: [
      requirementResult(
        "req-side-1",
        "Required Side 1 acting scene",
        "material",
        "mandatory",
        "present",
        "complete",
        "achieved",
        "The required Side 1 acting scene is present and complete.",
        "supports_submission",
        "preserve",
        "Preserve the clear Side 1 structure in the final export.",
      ),
      requirementResult(
        "req-song",
        "Contemporary legit MT song",
        "material",
        "mandatory",
        "present",
        "complete",
        "achieved",
        "The contemporary legit MT song is present and complete.",
        "supports_submission",
        "preserve",
        "Preserve the complete song arc and final phrase.",
      ),
      requirementResult(
        "req-continuous-video",
        "One continuous video containing the full package",
        "admin_process",
        "mandatory",
        "present",
        "complete",
        "achieved",
        "Side 1 and song appear in one continuous final video.",
        "supports_submission",
        "final_check",
        "Confirm the continuous export plays through before upload.",
      ),
      requirementResult(
        "req-one-file",
        "One final checked file",
        "admin_process",
        "mandatory",
        "not_assessable",
        "not_applicable",
        "mostly_achieved",
        "The material package is complete; one-file upload remains a final admin check.",
        "final_check",
        "final_check",
        "Export one final checked file after the playback check.",
      ),
      requirementResult(
        "req-landscape-framing",
        "Landscape close-up/head-and-shoulders framing",
        "technical",
        "mandatory",
        "present",
        "complete",
        "achieved",
        "Framing/orientation are assessable and support submission.",
        "supports_submission",
        "preserve",
        "Preserve the current framing and audio balance.",
      ),
      requirementResult(
        "req-file-name",
        "File naming instruction",
        "admin_process",
        "mandatory",
        "not_assessable",
        "not_applicable",
        "mostly_achieved",
        "Filename remains a final upload check, not a material blocker.",
        "final_check",
        "final_check",
        "Check the requested filename and deadline before upload.",
      ),
    ],
  },
  readiness_score_judgement: {
    decision: "submit",
    headline: "Submit: strong complete professional package.",
    rationale: [
      "The required Side 1 and song are present and complete.",
      "Final filename/upload checks remain admin steps, not submission blockers.",
    ],
    confidence: "high",
    performance_quality_score: 92,
    brief_completion_score: 94,
    overall_submission_readiness_score: 91,
    score_band_label: "submit_strong_submission",
    score_explanation:
      "The readiness score reflects a brief-complete professional submission: performance quality is strong, brief completion is verified, technical assessability supports review, and remaining work is final upload checking.",
    brief_blocker_override: false,
    performance_quality_summary:
      "Specific acting choices and a complete song arc support the professional level.",
    brief_completion_summary:
      "Mandatory material is complete; filename/upload are final checks only.",
    technical_assessability_summary: "Audio/framing are assessable and support submission.",
    selected_level_calibration_summary:
      "At professional level, the tape is submit-ready with useful polish notes rather than a retake requirement.",
    professional_nuance_summary:
      "The strongest value is the integrated scene-to-song package; optional polish is about precision, not completion.",
    category_scores: [
      {
        category_id: "brief_adherence",
        score: 94,
        score_basis:
          "Required Side 1, song and continuous package are verified; upload naming remains a final check.",
        what_works: "Mandatory material is present and complete.",
        why_not_full_score: "Final admin checks still need confirmation before upload.",
        close_gap: "Confirm filename, deadline and full playback.",
        confidence: "high",
        blocked_or_not_assessable_reason: null,
      },
      {
        category_id: "acting",
        score: 91,
        score_basis: "Side 1 is present with clear objective and playable stakes.",
        what_works: "Scene partner focus and beat structure read clearly.",
        why_not_full_score: "Keep the final turn precise rather than adding extra emphasis.",
        close_gap: "Sharpen the last beat only if retaking for polish.",
        confidence: "high",
        blocked_or_not_assessable_reason: null,
      },
      {
        category_id: "vocal",
        score: 92,
        score_basis: "Song is complete with a coherent legit MT arc.",
        what_works: "The lyric shape and final phrase are clear.",
        why_not_full_score: "Optional polish is diction specificity in the middle phrase.",
        close_gap: "Clarify the middle consonants without changing the take's shape.",
        confidence: "high",
        blocked_or_not_assessable_reason: null,
      },
      {
        category_id: "audio",
        score: 90,
        score_basis: "Audio is assessable across scene and song.",
        what_works: "Voice remains clear enough for review.",
        why_not_full_score: "No material audio blocker; only final playback check remains.",
        close_gap: "Playback-check the export before upload.",
        confidence: "high",
        blocked_or_not_assessable_reason: null,
      },
      {
        category_id: "technical",
        score: 89,
        score_basis: "Landscape close-up/head-and-shoulders framing is assessable.",
        what_works: "Camera readability supports the package.",
        why_not_full_score: "Final export review should confirm framing holds through the song.",
        close_gap: "Check the final file once before upload.",
        confidence: "high",
        blocked_or_not_assessable_reason: null,
      },
    ],
    category_rationale: {},
    component_scores: [
      {
        component_type: "acting_scene",
        linked_requirement_ids: ["req-side-1"],
        observed_status: "present",
        completion_status: "complete",
        score: 91,
        score_basis: "Side 1 is present and assessable with clear scene structure.",
        confidence: "high",
        cannot_score_reason: null,
      },
      {
        component_type: "song",
        linked_requirement_ids: ["req-song"],
        observed_status: "present",
        completion_status: "complete",
        score: 92,
        score_basis: "Song is present and complete with a coherent arc.",
        confidence: "high",
        cannot_score_reason: null,
      },
      {
        component_type: "package",
        linked_requirement_ids: ["req-continuous-video"],
        observed_status: "present",
        completion_status: "complete",
        score: 90,
        score_basis: "Side 1 and song work as a complete MT package.",
        confidence: "high",
        cannot_score_reason: null,
      },
    ],
    component_score_notes: [
      "Acting and song are scored from verified observed components.",
      "Package score reflects completion plus professional integration.",
    ],
    score_contradiction_warnings: [],
    repair_prompt_status: "not_needed",
  },
} as const;

const fixItem = (
  id: string,
  title: string,
  exact_action: string,
  urgency = "low",
  source_category = "polish",
) => ({
  id,
  title,
  issue: title,
  why_it_matters: "This follows from verified S10 evidence, not a mandatory blocker.",
  exact_action,
  source_category,
  urgency,
  submission_impact: urgency === "optional" ? "optional_polish" : "final_check",
  linked_requirement_ids: id.includes("song") ? ["req-song"] : ["req-side-1"],
  linked_matrix_result_ids: id.includes("song") ? ["req-song"] : ["req-side-1"],
  linked_component_verification_ids: id.includes("song") ? ["cv-song"] : ["cv-side-1"],
  linked_readiness_reason_ids: [],
  evidence_summary: exact_action,
  confidence: "high",
  is_fix_first_candidate: false,
  is_generic_fallback: false,
  source_authority: "s10_ai_authored",
  legacy_source_used: false,
});

export const s10StrongCompleteProfessionalExpectedReportModules = {
  ...s10StrongCompleteProfessionalExpectedModules,
  s10_fix_hierarchy: {
    fix_first: null,
    priority_fixes: [
      fixItem(
        "polish-final-beat",
        "Optional polish: keep the final scene beat precise.",
        "Only retake if you can sharpen the last beat without disturbing the complete package.",
        "optional",
      ),
    ],
    must_fix_before_submitting: [],
    should_improve_if_retaking: [
      fixItem(
        "polish-song-diction",
        "Optional polish: clarify the middle song phrase.",
        "If retaking for polish, keep the song arc and clarify the middle consonants.",
        "optional",
        "performance",
      ),
    ],
    optional_polish: [
      fixItem(
        "polish-final-beat",
        "Optional polish: keep the final scene beat precise.",
        "Only retake if you can sharpen the last beat without disturbing the complete package.",
        "optional",
      ),
    ],
    preserve: [
      fixItem(
        "preserve-package",
        "Preserve the complete Side 1 plus song package.",
        "Keep the achieved package structure intact for the final export.",
        "low",
        "brief",
      ),
    ],
    do_not_overfix: [
      fixItem(
        "do-not-overfix-package",
        "Do not rework the achieved package without a concrete polish reason.",
        "Submit after final file/upload/playback checks unless you are addressing the optional polish point.",
        "low",
        "polish",
      ),
    ],
    action_contradiction_warnings: [],
  },
  s10_next_action_plan: {
    submit_checklist: [
      "Confirm the final file contains the complete Side 1 and complete song.",
      "Check the requested filename, upload link and deadline.",
      "Playback-check the exported file from start to finish.",
    ],
    retake_plan: [],
    final_checks: ["Final file/upload/deadline/playback check."],
    playback_checks: ["Check the full file plays through with no abrupt cut-off."],
    do_not_overfix: [
      "Do not rework the achieved package unless addressing a concrete optional polish point.",
    ],
    if_time_is_short_guidance: [
      "If deadline is close, submit after final file/upload/playback checks.",
    ],
    no_retake_needed_reason:
      "No mandatory fix before submission; optional polish is not required for readiness.",
    confidence: "high",
  },
  s10_professional_critique: {
    summary:
      "The report value is the complete professional package plus specific polish choices, not a generic no-blocker note.",
    performance_strengths: [
      {
        id: "strength-acting-song-integration",
        title: "Specific acting-through-song package integration.",
        detail:
          "The Side 1 objective carries into the song so the package reads as one professional audition unit.",
        why_it_matters:
          "It helps the panel see performance continuity rather than two disconnected clips.",
        evidence_summary: "Verified Side 1 and verified complete song are both present.",
        source_category: "performance",
        linked_requirement_ids: ["req-side-1", "req-song"],
        linked_component_verification_ids: ["cv-side-1", "cv-song"],
        linked_matrix_result_ids: ["req-side-1", "req-song"],
        linked_readiness_reason_ids: [],
        linked_fix_ids: [],
        confidence: "high",
        is_component_verified: true,
        component_status: "present",
        applies_to_observed_portion_only: false,
        is_generic_fallback: false,
      },
    ],
    brief_package_strengths: [
      {
        id: "strength-complete-package",
        title: "Complete required Side 1 plus song package.",
        detail: "The mandatory materials are present and ready for final upload checks.",
        why_it_matters: "Completion supports a submit-ready recommendation.",
        evidence_summary: "S10 component verification marks Side 1, song and package complete.",
        source_category: "package",
        linked_requirement_ids: ["req-side-1", "req-song", "req-continuous-video"],
        linked_component_verification_ids: ["cv-side-1", "cv-song", "cv-continuous-video"],
        linked_matrix_result_ids: ["req-side-1", "req-song", "req-continuous-video"],
        linked_readiness_reason_ids: [],
        linked_fix_ids: [],
        confidence: "high",
        is_component_verified: true,
        component_status: "present",
        applies_to_observed_portion_only: false,
        is_generic_fallback: false,
      },
    ],
    technical_presentation_strengths: [
      {
        id: "strength-framing-audio",
        title: "Assessable audio and camera readability.",
        detail: "The close-up/head-and-shoulders framing and audio support professional review.",
        why_it_matters: "It keeps focus on the acting/song work.",
        evidence_summary: "Audio and framing are assessable across the observed package.",
        source_category: "technical",
        linked_requirement_ids: ["req-landscape-framing"],
        linked_component_verification_ids: ["cv-landscape-framing"],
        linked_matrix_result_ids: ["req-landscape-framing"],
        linked_readiness_reason_ids: [],
        linked_fix_ids: [],
        confidence: "high",
        is_component_verified: true,
        component_status: "present",
        applies_to_observed_portion_only: false,
        is_generic_fallback: false,
      },
    ],
    vocal_or_singing_strengths: [],
    acting_strengths: [],
    movement_or_physical_strengths: [],
    professional_presentation_notes: [
      {
        id: "presentation-note-final-check",
        title: "Professional nuance: final upload discipline.",
        detail:
          "The submission is strong; the remaining professional move is a calm final filename, deadline and playback check.",
        evidence_summary: "Package is achieved and final admin checks remain.",
        source_category: "presentation",
        confidence: "high",
        is_generic_fallback: false,
      },
    ],
    preserve: [
      {
        id: "preserve-scene-song-arc",
        title: "Preserve the scene-to-song arc.",
        detail: "Keep the objective, vocal line and camera readability working as one package.",
        evidence_summary: "Verified Side 1 and song are complete.",
        why_to_preserve: "It is the strongest professional value in the take.",
        linked_component_verification_ids: ["cv-side-1", "cv-song"],
        confidence: "high",
        is_generic_fallback: false,
      },
    ],
    do_not_overfix: [
      {
        id: "do-not-overfix-package",
        title: "Do not rework the achieved package without a concrete polish reason.",
        detail: "Avoid a retake loop; use final checks unless you can improve the optional polish.",
        evidence_summary: "No mandatory blocker exists.",
        why_to_preserve: "The package is already submit-ready.",
        linked_component_verification_ids: ["cv-side-1", "cv-song"],
        confidence: "high",
        is_generic_fallback: false,
      },
    ],
    critique_limitations: [],
    contradiction_warnings: [],
  },
  s10_technique_commentary: {
    summary: "Technique commentary is assessable across verified acting, song and package work.",
    acting: {
      status: "assessable",
      headline: "Acting objective and scene partner focus are clear.",
      observations: [
        {
          id: "tech-acting-objective",
          technique_area: "acting",
          title: "Clear playable objective in the Side 1.",
          detail: "The scene stays active without needing extra emphasis.",
          evidence_summary: "Verified Side 1 acting scene is present.",
          linked_requirement_ids: ["req-side-1"],
          linked_component_verification_ids: ["cv-side-1"],
          linked_matrix_result_ids: ["req-side-1"],
          linked_readiness_reason_ids: [],
          linked_strength_ids: ["strength-acting-song-integration"],
          linked_fix_ids: [],
          linked_timestamp_refs: ["00:06-01:04"],
          component_status: "present",
          applies_to_observed_portion_only: false,
          confidence: "high",
          is_named_authority_claim: false,
          is_medical_or_health_claim: false,
          is_body_or_appearance_claim: false,
          is_casting_outcome_claim: false,
          is_generic_fallback: false,
        },
      ],
      what_is_working: ["Objective and listening read clearly in the verified Side 1."],
      what_could_improve: ["Optional polish is the precision of the final turn."],
      practical_actions: ["Keep the final Side 1 beat precise if retaking for polish."],
      preserve: ["Preserve the direct scene partner focus."],
      not_assessable_reason: null,
      confidence: "high",
    },
    vocal_singing: {
      status: "assessable",
      headline: "The song has a complete, coherent legit MT arc.",
      observations: [
        {
          id: "tech-song-arc",
          technique_area: "vocal_singing",
          title: "Complete song arc with clear final phrase.",
          detail: "The ending is present, so the note is about polish rather than completion.",
          evidence_summary: "Verified song is complete.",
          linked_requirement_ids: ["req-song"],
          linked_component_verification_ids: ["cv-song"],
          linked_matrix_result_ids: ["req-song"],
          linked_readiness_reason_ids: [],
          linked_strength_ids: ["strength-acting-song-integration"],
          linked_fix_ids: [],
          linked_timestamp_refs: ["01:05-02:15"],
          component_status: "present",
          applies_to_observed_portion_only: false,
          confidence: "high",
          is_named_authority_claim: false,
          is_medical_or_health_claim: false,
          is_body_or_appearance_claim: false,
          is_casting_outcome_claim: false,
          is_generic_fallback: false,
        },
      ],
      what_is_working: ["The complete song ending supports submission readiness."],
      what_could_improve: ["Optional polish is clearer diction in the middle phrase."],
      practical_actions: ["Keep the song ending intact if retaking for polish."],
      preserve: ["Preserve the final phrase and overall arc."],
      not_assessable_reason: null,
      confidence: "high",
    },
    movement_dance: {
      status: "not_applicable",
      headline: "Movement/dance was not required by this fixture.",
      observations: [],
      what_is_working: [],
      what_could_improve: [],
      practical_actions: [],
      preserve: [],
      not_assessable_reason: null,
      confidence: "medium",
    },
    musical_theatre_package: {
      status: "assessable",
      headline: "The MT package integrates verified Side 1 and complete song.",
      observations: [],
      what_is_working: ["Scene and song read as one professional package."],
      what_could_improve: ["Optional polish should not disturb package completion."],
      practical_actions: ["Submit after final file/upload/playback checks."],
      preserve: ["Preserve the integrated package shape."],
      not_assessable_reason: null,
      confidence: "high",
    },
    self_tape_presentation: {
      status: "assessable",
      headline: "Self-tape presentation supports review.",
      observations: [],
      what_is_working: ["Audio and framing are assessable."],
      what_could_improve: ["Final playback check only."],
      practical_actions: ["Check the export once before upload."],
      preserve: ["Preserve the current camera readability."],
      not_assessable_reason: null,
      confidence: "high",
    },
    commercial_screen_task: {
      status: "not_applicable",
      headline: "",
      observations: [],
      what_is_working: [],
      what_could_improve: [],
      practical_actions: [],
      preserve: [],
      not_assessable_reason: null,
      confidence: "low",
    },
    limitations: [],
    contradiction_warnings: [],
  },
  s10_timestamped_commentary: {
    summary:
      "Timestamped notes highlight verified Side 1 and song moments without inventing missing material.",
    notes: [
      {
        id: "note-side-1-opening",
        timecode: "00:06",
        start_time: "00:06",
        end_time: "00:18",
        time_band_label: "Opening Side 1 beat",
        display_label: "00:06",
        timestamp_precision: "exact",
        section: "technique",
        title: "Side 1 starts with a clear playable objective.",
        detail: "Preserve the direct focus at the start of the acting side.",
        action: "Keep this opening beat intact.",
        evidence_summary: "Verified Side 1 component begins at 00:06.",
        linked_requirement_ids: ["req-side-1"],
        linked_observed_sequence_ids: ["seq-side-1"],
        linked_component_verification_ids: ["cv-side-1"],
        linked_matrix_result_ids: ["req-side-1"],
        linked_fix_ids: [],
        linked_strength_ids: ["strength-acting-song-integration"],
        linked_technique_observation_ids: ["tech-acting-objective"],
        component_type: "acting_scene",
        component_status: "present",
        applies_to_observed_portion_only: false,
        is_exact_timestamp_supported: true,
        is_legacy_timestamp_projection: false,
        note_source_authority: "s10_ai_authored",
        legacy_source_used: false,
        is_missing_component_note: false,
        is_projection_safe: true,
        confidence: "high",
        is_generic_fallback: false,
      },
      {
        id: "note-song-ending",
        timecode: "02:05",
        start_time: "02:05",
        end_time: "02:15",
        time_band_label: "Song ending",
        display_label: "02:05",
        timestamp_precision: "exact",
        section: "strength",
        title: "The song ending is present and should be preserved.",
        detail: "This is a submit-readiness strength, not a completion concern.",
        action: "Playback-check the final export to preserve this ending.",
        evidence_summary: "Verified complete song runs through the ending.",
        linked_requirement_ids: ["req-song"],
        linked_observed_sequence_ids: ["seq-song"],
        linked_component_verification_ids: ["cv-song"],
        linked_matrix_result_ids: ["req-song"],
        linked_fix_ids: [],
        linked_strength_ids: ["strength-acting-song-integration"],
        linked_technique_observation_ids: ["tech-song-arc"],
        component_type: "song",
        component_status: "present",
        applies_to_observed_portion_only: false,
        is_exact_timestamp_supported: true,
        is_legacy_timestamp_projection: false,
        note_source_authority: "s10_ai_authored",
        legacy_source_used: false,
        is_missing_component_note: false,
        is_projection_safe: true,
        confidence: "high",
        is_generic_fallback: false,
      },
    ],
    component_ranges: [
      {
        component_type: "acting_scene",
        label: "Required Side 1 acting scene",
        start_time: "00:06",
        end_time: "01:04",
        timestamp_precision: "exact",
        observed_status: "present",
        completion_status: "complete",
        linked_requirement_ids: ["req-side-1"],
        evidence_summary: "Verified Side 1 range.",
        confidence: "high",
      },
      {
        component_type: "song",
        label: "Contemporary legit MT song",
        start_time: "01:05",
        end_time: "02:15",
        timestamp_precision: "exact",
        observed_status: "present",
        completion_status: "complete",
        linked_requirement_ids: ["req-song"],
        evidence_summary: "Verified song range.",
        confidence: "high",
      },
    ],
    missing_or_unobserved_components: [],
    timestamp_limitations: [],
    projection_notes: [
      {
        timestamp: "00:06",
        note: "Side 1 starts with a clear playable objective.",
      },
      {
        timestamp: "02:05",
        note: "The song ending is present and should be preserved.",
      },
    ],
    legacy_projection_blocked_count: 0,
    exact_timestamp_supported_count: 2,
    time_banded_note_count: 0,
    order_only_note_count: 0,
    missing_component_note_count: 0,
    contradiction_warnings: [],
  },
} as const;

export const s10StrongCompleteProfessionalExpectedViewModel = {
  required_authoritative_sections: [
    "readiness_header",
    "submission_guidance",
    "score_summary",
    "brief_achievement",
    "observed_tape",
    "component_breakdown",
    "fix_hierarchy",
    "next_action_plan",
    "strengths_and_preserve",
    "technique_commentary",
    "timestamped_commentary",
  ],
  allowed_route_content: [
    "Submit: strong complete professional package",
    "mostly achieved",
    "Required Side 1 acting scene",
    "Contemporary legit MT song",
    "Specific acting-through-song package integration",
    "Preserve the scene-to-song arc",
    "Acting objective and scene partner focus are clear",
    "The MT package integrates verified Side 1 and complete song",
    "00:06",
    "02:05",
    "Confirm the final file contains the complete Side 1 and complete song",
    "Do not rework the achieved package",
  ],
  forbidden_route_content: [
    "No single public-safe priority fix was available",
    "This affects readability, not talent",
    "Preserve the clearest choices already captured",
    "missing Side 1",
    "Side 1 is missing",
    "song/package is incomplete",
    "Retake required if possible",
    "unsupported audio blocker",
    "report polish unavailable",
    "Strong choices.",
  ],
} as const;

export function buildS10StrongCompleteProfessionalReportInput() {
  return {
    ...structuredClone(s10StrongCompleteProfessionalLegacySnapshot),
    brief_context: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.brief_context,
    ),
    brief_requirements: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.brief_requirements,
    ),
    observed_tape_sequence: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.observed_tape_sequence,
    ),
    component_verifications: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.component_verifications,
    ),
    media_observation_summary: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.media_observation_summary,
    ),
    brief_achievement_matrix: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.brief_achievement_matrix,
    ),
    readiness_score_judgement: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.readiness_score_judgement,
    ),
    s10_fix_hierarchy: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.s10_fix_hierarchy,
    ),
    s10_next_action_plan: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.s10_next_action_plan,
    ),
    s10_professional_critique: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.s10_professional_critique,
    ),
    s10_technique_commentary: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.s10_technique_commentary,
    ),
    s10_timestamped_commentary: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.s10_timestamped_commentary,
    ),
  };
}

export function buildS10StrongCompleteProfessionalViewContext() {
  return {
    briefContext: structuredClone(s10StrongCompleteProfessionalExpectedReportModules.brief_context),
    briefRequirements: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.brief_requirements,
    ),
    observedTapeSequence: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.observed_tape_sequence,
    ),
    componentVerifications: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.component_verifications,
    ),
    mediaObservationSummary: structuredClone(
      s10StrongCompleteProfessionalExpectedReportModules.media_observation_summary,
    ),
  };
}
