/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditionAuditionIdRouteImport } from './routes/audition.$auditionId'
import { Route as AdminStorageDownloadsRouteImport } from './routes/admin/storage-downloads'
import { Route as ApiPublicReconcileStaleTakesRouteImport } from './routes/api/public/reconcile-stale-takes'
import { Route as ApiPublicMuxWebhookRouteImport } from './routes/api/public/mux-webhook'
import { Route as ApiPublicAdminConfigRouteImport } from './routes/api/public/admin-config'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditionAuditionIdRoute = AuditionAuditionIdRouteImport.update({
  id: '/audition/$auditionId',
  path: '/audition/$auditionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStorageDownloadsRoute = AdminStorageDownloadsRouteImport.update({
  id: '/admin/storage-downloads',
  path: '/admin/storage-downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReconcileStaleTakesRoute =
  ApiPublicReconcileStaleTakesRouteImport.update({
    id: '/api/public/reconcile-stale-takes',
    path: '/api/public/reconcile-stale-takes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMuxWebhookRoute = ApiPublicMuxWebhookRouteImport.update({
  id: '/api/public/mux-webhook',
  path: '/api/public/mux-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminConfigRoute = ApiPublicAdminConfigRouteImport.update({
  id: '/api/public/admin-config',
  path: '/api/public/admin-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/storage-downloads': typeof AdminStorageDownloadsRoute
  '/audition/$auditionId': typeof AuditionAuditionIdRoute
  '/api/public/admin-config': typeof ApiPublicAdminConfigRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/reconcile-stale-takes': typeof ApiPublicReconcileStaleTakesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/storage-downloads': typeof AdminStorageDownloadsRoute
  '/audition/$auditionId': typeof AuditionAuditionIdRoute
  '/api/public/admin-config': typeof ApiPublicAdminConfigRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/reconcile-stale-takes': typeof ApiPublicReconcileStaleTakesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/storage-downloads': typeof AdminStorageDownloadsRoute
  '/audition/$auditionId': typeof AuditionAuditionIdRoute
  '/api/public/admin-config': typeof ApiPublicAdminConfigRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/reconcile-stale-takes': typeof ApiPublicReconcileStaleTakesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/admin/storage-downloads'
    | '/audition/$auditionId'
    | '/api/public/admin-config'
    | '/api/public/mux-webhook'
    | '/api/public/reconcile-stale-takes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/admin/storage-downloads'
    | '/audition/$auditionId'
    | '/api/public/admin-config'
    | '/api/public/mux-webhook'
    | '/api/public/reconcile-stale-takes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/admin/storage-downloads'
    | '/audition/$auditionId'
    | '/api/public/admin-config'
    | '/api/public/mux-webhook'
    | '/api/public/reconcile-stale-takes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  AdminStorageDownloadsRoute: typeof AdminStorageDownloadsRoute
  AuditionAuditionIdRoute: typeof AuditionAuditionIdRoute
  ApiPublicAdminConfigRoute: typeof ApiPublicAdminConfigRoute
  ApiPublicMuxWebhookRoute: typeof ApiPublicMuxWebhookRoute
  ApiPublicReconcileStaleTakesRoute: typeof ApiPublicReconcileStaleTakesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audition/$auditionId': {
      id: '/audition/$auditionId'
      path: '/audition/$auditionId'
      fullPath: '/audition/$auditionId'
      preLoaderRoute: typeof AuditionAuditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/storage-downloads': {
      id: '/admin/storage-downloads'
      path: '/admin/storage-downloads'
      fullPath: '/admin/storage-downloads'
      preLoaderRoute: typeof AdminStorageDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reconcile-stale-takes': {
      id: '/api/public/reconcile-stale-takes'
      path: '/api/public/reconcile-stale-takes'
      fullPath: '/api/public/reconcile-stale-takes'
      preLoaderRoute: typeof ApiPublicReconcileStaleTakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mux-webhook': {
      id: '/api/public/mux-webhook'
      path: '/api/public/mux-webhook'
      fullPath: '/api/public/mux-webhook'
      preLoaderRoute: typeof ApiPublicMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-config': {
      id: '/api/public/admin-config'
      path: '/api/public/admin-config'
      fullPath: '/api/public/admin-config'
      preLoaderRoute: typeof ApiPublicAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  AdminStorageDownloadsRoute: AdminStorageDownloadsRoute,
  AuditionAuditionIdRoute: AuditionAuditionIdRoute,
  ApiPublicAdminConfigRoute: ApiPublicAdminConfigRoute,
  ApiPublicMuxWebhookRoute: ApiPublicMuxWebhookRoute,
  ApiPublicReconcileStaleTakesRoute: ApiPublicReconcileStaleTakesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
