/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundCreditPolicyRouteImport } from './routes/legal/refund-credit-policy'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalAiReportDisclaimerRouteImport } from './routes/legal/ai-report-disclaimer'
import { Route as AuditionAuditionIdRouteImport } from './routes/audition.$auditionId'
import { Route as AdminStorageDownloadsRouteImport } from './routes/admin/storage-downloads'
import { Route as ApiPublicReconcileStaleTakesRouteImport } from './routes/api/public/reconcile-stale-takes'
import { Route as ApiPublicMuxWebhookRouteImport } from './routes/api/public/mux-webhook'
import { Route as ApiPublicAdminProductCatalogueRouteImport } from './routes/api/public/admin-product-catalogue'
import { Route as ApiPublicAdminConfigRouteImport } from './routes/api/public/admin-config'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundCreditPolicyRoute = LegalRefundCreditPolicyRouteImport.update({
  id: '/legal/refund-credit-policy',
  path: '/legal/refund-credit-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAiReportDisclaimerRoute = LegalAiReportDisclaimerRouteImport.update({
  id: '/legal/ai-report-disclaimer',
  path: '/legal/ai-report-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditionAuditionIdRoute = AuditionAuditionIdRouteImport.update({
  id: '/audition/$auditionId',
  path: '/audition/$auditionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStorageDownloadsRoute = AdminStorageDownloadsRouteImport.update({
  id: '/admin/storage-downloads',
  path: '/admin/storage-downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReconcileStaleTakesRoute =
  ApiPublicReconcileStaleTakesRouteImport.update({
    id: '/api/public/reconcile-stale-takes',
    path: '/api/public/reconcile-stale-takes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMuxWebhookRoute = ApiPublicMuxWebhookRouteImport.update({
  id: '/api/public/mux-webhook',
  path: '/api/public/mux-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminProductCatalogueRoute =
  ApiPublicAdminProductCatalogueRouteImport.update({
    id: '/api/public/admin-product-catalogue',
    path: '/api/public/admin-product-catalogue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminConfigRoute = ApiPublicAdminConfigRouteImport.update({
  id: '/api/public/admin-config',
  path: '/api/public/admin-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/storage-downloads': typeof AdminStorageDownloadsRoute
  '/audition/$auditionId': typeof AuditionAuditionIdRoute
  '/legal/ai-report-disclaimer': typeof LegalAiReportDisclaimerRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund-credit-policy': typeof LegalRefundCreditPolicyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/admin-config': typeof ApiPublicAdminConfigRoute
  '/api/public/admin-product-catalogue': typeof ApiPublicAdminProductCatalogueRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/reconcile-stale-takes': typeof ApiPublicReconcileStaleTakesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/storage-downloads': typeof AdminStorageDownloadsRoute
  '/audition/$auditionId': typeof AuditionAuditionIdRoute
  '/legal/ai-report-disclaimer': typeof LegalAiReportDisclaimerRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund-credit-policy': typeof LegalRefundCreditPolicyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/admin-config': typeof ApiPublicAdminConfigRoute
  '/api/public/admin-product-catalogue': typeof ApiPublicAdminProductCatalogueRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/reconcile-stale-takes': typeof ApiPublicReconcileStaleTakesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/admin/storage-downloads': typeof AdminStorageDownloadsRoute
  '/audition/$auditionId': typeof AuditionAuditionIdRoute
  '/legal/ai-report-disclaimer': typeof LegalAiReportDisclaimerRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund-credit-policy': typeof LegalRefundCreditPolicyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/admin-config': typeof ApiPublicAdminConfigRoute
  '/api/public/admin-product-catalogue': typeof ApiPublicAdminProductCatalogueRoute
  '/api/public/mux-webhook': typeof ApiPublicMuxWebhookRoute
  '/api/public/reconcile-stale-takes': typeof ApiPublicReconcileStaleTakesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/admin/storage-downloads'
    | '/audition/$auditionId'
    | '/legal/ai-report-disclaimer'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund-credit-policy'
    | '/legal/terms'
    | '/api/public/admin-config'
    | '/api/public/admin-product-catalogue'
    | '/api/public/mux-webhook'
    | '/api/public/reconcile-stale-takes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/admin/storage-downloads'
    | '/audition/$auditionId'
    | '/legal/ai-report-disclaimer'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund-credit-policy'
    | '/legal/terms'
    | '/api/public/admin-config'
    | '/api/public/admin-product-catalogue'
    | '/api/public/mux-webhook'
    | '/api/public/reconcile-stale-takes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/new'
    | '/admin/storage-downloads'
    | '/audition/$auditionId'
    | '/legal/ai-report-disclaimer'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund-credit-policy'
    | '/legal/terms'
    | '/api/public/admin-config'
    | '/api/public/admin-product-catalogue'
    | '/api/public/mux-webhook'
    | '/api/public/reconcile-stale-takes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  AdminStorageDownloadsRoute: typeof AdminStorageDownloadsRoute
  AuditionAuditionIdRoute: typeof AuditionAuditionIdRoute
  LegalAiReportDisclaimerRoute: typeof LegalAiReportDisclaimerRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundCreditPolicyRoute: typeof LegalRefundCreditPolicyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiPublicAdminConfigRoute: typeof ApiPublicAdminConfigRoute
  ApiPublicAdminProductCatalogueRoute: typeof ApiPublicAdminProductCatalogueRoute
  ApiPublicMuxWebhookRoute: typeof ApiPublicMuxWebhookRoute
  ApiPublicReconcileStaleTakesRoute: typeof ApiPublicReconcileStaleTakesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund-credit-policy': {
      id: '/legal/refund-credit-policy'
      path: '/legal/refund-credit-policy'
      fullPath: '/legal/refund-credit-policy'
      preLoaderRoute: typeof LegalRefundCreditPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/ai-report-disclaimer': {
      id: '/legal/ai-report-disclaimer'
      path: '/legal/ai-report-disclaimer'
      fullPath: '/legal/ai-report-disclaimer'
      preLoaderRoute: typeof LegalAiReportDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audition/$auditionId': {
      id: '/audition/$auditionId'
      path: '/audition/$auditionId'
      fullPath: '/audition/$auditionId'
      preLoaderRoute: typeof AuditionAuditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/storage-downloads': {
      id: '/admin/storage-downloads'
      path: '/admin/storage-downloads'
      fullPath: '/admin/storage-downloads'
      preLoaderRoute: typeof AdminStorageDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reconcile-stale-takes': {
      id: '/api/public/reconcile-stale-takes'
      path: '/api/public/reconcile-stale-takes'
      fullPath: '/api/public/reconcile-stale-takes'
      preLoaderRoute: typeof ApiPublicReconcileStaleTakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mux-webhook': {
      id: '/api/public/mux-webhook'
      path: '/api/public/mux-webhook'
      fullPath: '/api/public/mux-webhook'
      preLoaderRoute: typeof ApiPublicMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-product-catalogue': {
      id: '/api/public/admin-product-catalogue'
      path: '/api/public/admin-product-catalogue'
      fullPath: '/api/public/admin-product-catalogue'
      preLoaderRoute: typeof ApiPublicAdminProductCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-config': {
      id: '/api/public/admin-config'
      path: '/api/public/admin-config'
      fullPath: '/api/public/admin-config'
      preLoaderRoute: typeof ApiPublicAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  AdminStorageDownloadsRoute: AdminStorageDownloadsRoute,
  AuditionAuditionIdRoute: AuditionAuditionIdRoute,
  LegalAiReportDisclaimerRoute: LegalAiReportDisclaimerRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundCreditPolicyRoute: LegalRefundCreditPolicyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiPublicAdminConfigRoute: ApiPublicAdminConfigRoute,
  ApiPublicAdminProductCatalogueRoute: ApiPublicAdminProductCatalogueRoute,
  ApiPublicMuxWebhookRoute: ApiPublicMuxWebhookRoute,
  ApiPublicReconcileStaleTakesRoute: ApiPublicReconcileStaleTakesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
