// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClientDatabase } from "./client-database";
import {
  requireSupabasePublicRuntimeConfig,
  SupabasePublicRuntimeConfigError,
} from "./public-runtime";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    let publicConfig: ReturnType<typeof requireSupabasePublicRuntimeConfig>;
    try {
      publicConfig = requireSupabasePublicRuntimeConfig();
    } catch (error) {
      if (error instanceof SupabasePublicRuntimeConfigError) {
        console.error("[supabase-auth] public_runtime_config_missing", {
          operation: "require_supabase_auth",
          code: "public_supabase_misconfigured",
          ...error.diagnostics,
        });
      }
      throw new Response(
        "Missing Supabase environment variables. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set.",
        { status: 500 },
      );
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Response("Unauthorized: No request headers available", { status: 401 });
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Response("Unauthorized: No authorization header provided", { status: 401 });
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Response("Unauthorized: Only Bearer tokens are supported", { status: 401 });
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Response("Unauthorized: No token provided", { status: 401 });
    }

    const supabase = createClient<SupabaseClientDatabase>(
      publicConfig.supabaseUrl,
      publicConfig.publishableKey,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      },
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response("Unauthorized: Invalid token", { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response("Unauthorized: No user ID found in token", { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
